#!/usr/bin/env bash
# Sync every skill in this repo (master source) to every install root,
# then SHA-verify the result.
#
# Topology — N skills (skills/<name>/) x the harness roots below:
#   skills/<name>/            -> ~/.agents/skills/<name>/
#                              -> ~/.claude/skills/<name>/
#                              -> ~/.zcode/skills/<name>/
#                              -> ~/.omp/agent/skills/<name>/
#                                 (omp-native root, priority-100 provider
#                                 — omp sessions load this copy)
#   skills/<name>/commands/<name>.md -> ~/.agents/commands/,
#                              ~/.claude/commands/, ~/.zcode/commands/
#                              — plus the bare names the skill opts into
#                              via its own commands/extra.txt (generic
#                              names in shared roots are an explicit
#                              per-skill opt-in, never a glob; a foreign
#                              file at any destination is refused, not
#                              clobbered; omp needs none —
#                              /skill:<name> auto-registers)
#                              — ~/.factory/commands/ too, gated on
#                              ~/.factory existing (Factory Droid's
#                              own command root; never fabricated,
#                              loud skip otherwise)
#   skills/<name>/agents/*.md -> ~/.claude/agents/ (as-is; the harness
#                                 reads Claude-style frontmatter directly)
#                              -> ~/.omp/agent/agents/ (regenerated with
#                                 omp frontmatter by tools/omp-defs.py —
#                                 omp skips ~/.claude/agents and its tool
#                                 registry is lowercase). Files named with
#                                 a leading underscore (shared prose, e.g.
#                                 _shared-protocol.md) are not roles and
#                                 are skipped. zcode gets no agents/
#                                 install step: SKILL.md § Spawn mechanics
#                                 documents it as having no
#                                 user-installable agent types, so it
#                                 only gets skills/ + commands/.
#                              -> ~/.config/opencode/agents/ and
#                                 ~/.factory/droids/ (OPTIONAL roots,
#                                 regenerated by tools/agent-defs.py:
#                                 opencode subagents / Factory droids).
#                                 Installed only when the harness's own
#                                 config home exists — sync never
#                                 fabricates a harness directory. Both
#                                 harnesses read skills from the
#                                 ~/.agents/skills compatibility root
#                                 already installed above.
#                              -> <repo>/agents/ (agy personas — COMMITTED
#                                 regenerate-only copies of the briefs:
#                                 the repo root is the plugin that
#                                 `agy plugin install` copies; agy owns
#                                 ~/.gemini/config/plugins itself).
#
# omp also reads ~/.agents/skills (its `agents` provider, priority 70),
# so that root alone would serve omp sessions; the ~/.omp copy makes
# every skill self-sufficient inside omp and wins omp's same-name dedup.
#
# A skill opts into this topology just by existing at skills/<name>/ with
# a SKILL.md — no registration step, no list to edit here.
#
# Run from anywhere: tools/sync.sh — edits always land in skills/<name>/
# first; this script is the only thing that copies out.
#
# Modes (FR-009): plain `tools/sync.sh` applies the plan; `--dry-run`
# prints the full plan — create/update/unchanged/delete/refuse per
# destination — and exits; `--check` reports refusals plus drift between
# the masters and what is installed. Neither mode writes a destination
# or records ownership.
set -euo pipefail

PKG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail=0

usage() {
  echo "usage: tools/sync.sh [--dry-run|--check]" >&2
}

DRY_RUN=0
CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --check) CHECK=1 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
  esac
  shift
done
if [ "$DRY_RUN" = 1 ] && [ "$CHECK" = 1 ]; then
  echo "ERROR: --dry-run and --check are mutually exclusive" >&2
  usage
  exit 2
fi

SKILLS_ROOTS=(
  "$HOME/.agents/skills"
  "$HOME/.claude/skills"
  "$HOME/.zcode/skills"
  "$HOME/.omp/agent/skills"
)
COMMANDS_ROOTS=(
  "$HOME/.agents/commands"
  "$HOME/.claude/commands"
  "$HOME/.zcode/commands"
)
CLAUDE_AGENTS_ROOT="$HOME/.claude/agents"
OMP_AGENTS_ROOT="$HOME/.omp/agent/agents"
# Optional harness agent-def roots — active only when the harness's own
# config home exists (see the install loop).
OPENCODE_AGENTS_ROOT="$HOME/.config/opencode/agents"
DROID_AGENTS_ROOT="$HOME/.factory/droids"
DROID_COMMANDS_ROOT="$HOME/.factory/commands"

# Bare-named commands a skill ships beyond its collision-proof
# <name>.md router: an explicit `commands/extra.txt` in the skill (one
# line, space-separated bare names — a reviewed file inside the skill
# dir, never a glob; ADR-013). Generic names (spec.md, plan.md, ...)
# land flat in shared global command roots, so the opt-in lives with
# the skill that pays for it, and a second skill wanting the same bare
# name is a rename-or-namespace decision.
extra_commands() {  # <skill-name> -> bare names on stdout
  local f="$PKG_ROOT/skills/$1/commands/extra.txt"
  if [ -f "$f" ]; then cat "$f"; fi
}

# Provenance ledger: every command root keeps the sha256 of each file
# this script deployed there (.spec-dev-kit-deployed — harnesses read
# only *.md, so the hidden file is inert). A destination that differs
# from the master is overwritten ONLY when its hash sits in the ledger
# (a previous deploy of ours, committed or not); anything else at the
# destination is foreign — refuse loudly, never clobber.
ledger_entry_matches() {  # <ledger-file> <command-name> <dest-file>
  [ -f "$1" ] || return 1
  local want
  want="$(shasum -a 256 < "$3" | cut -d' ' -f1)"
  awk -v n="$2" -v h="$want" '$1 == h && $2 == n {found = 1}
        END {exit found ? 0 : 1}' "$1"
}

ledger_record() {  # <ledger-file> <command-name> <master-file>
  local h
  h="$(shasum -a 256 < "$3" | cut -d' ' -f1)"
  # Rewrite via destination-local scratch renamed over the ledger, so
  # the ledger file itself never holds partial content (FR-007).
  if [ -f "$1" ]; then
    grep -v " $2\$" "$1" > "$1.tmp" || true
  else
    : > "$1.tmp"
  fi
  printf '%s %s\n' "$h" "$2" >> "$1.tmp"
  mv "$1.tmp" "$1"
}

sha() {  # <file> -> sha256 on stdout
  shasum -a 256 < "$1" | cut -d' ' -f1
}

LEDGER_NAME=".spec-dev-kit-deployed"

# Destination-local staging + atomic replacement (FR-007): content lands
# via rename from a scratch file in the destination's own directory, so
# a destination is never seen half-written. Scratch carries the
# LEDGER_NAME prefix — the installer-scratch namespace the sweep, the
# ledger rewrites, the verify pass, and tools/ownership.py's inventory
# all already exclude — so even a crash leftover can never be
# misclassified as a foreign file.
atomic_put() {  # <src> <dest>
  local tmp
  tmp="$(dirname "$2")/$LEDGER_NAME.tmp-$(basename "$2").tmp"
  rm -f "$tmp"
  cp -p "$1" "$tmp"
  mv "$tmp" "$2"
}

# Skills-tree provenance — the command roots' refuse-don't-clobber
# rule, applied to a whole installed directory. Every dest file is
# classified before anything is touched: a path the master still ships
# may be replaced only when identical or ledger-own (a previous deploy
# of ours); a path the master no longer ships is deleted only when its
# current hash is still the ledgered deployed hash; anything else is
# foreign — REFUSED loudly, and nothing in the tree is written or
# removed. Returns 1 when anything foreign was found.
sweep_tree() {  # <master-dir> <dest-dir> <ledger>
  local master="$1" dest="$2" ledger="$3" rel bad=0
  local stale=()
  [ -d "$dest" ] || return 0
  while IFS= read -r rel; do
    rel="${rel#./}"; [ -n "$rel" ] || continue
    if [ -f "$master/$rel" ]; then
      if cmp -s "$master/$rel" "$dest/$rel" \
         || ledger_entry_matches "$ledger" "$rel" "$dest/$rel"; then
        continue
      fi
      echo "REFUSE $dest/$rel — foreign file (differs from master, not a prior deploy); resolve manually"
      bad=1
    elif ledger_entry_matches "$ledger" "$rel" "$dest/$rel"; then
      stale+=("$rel")
    else
      echo "REFUSE $dest/$rel — foreign file (not shipped by the skill, not a prior deploy); resolve manually"
      bad=1
    fi
  done < <(cd "$dest" && find . -type f ! -name '.DS_Store' \
      ! -path '*/__pycache__/*' ! -name "$LEDGER_NAME*")
  [ "$bad" -eq 0 ] || return 1
  # bash 3.2 + set -u: expanding an empty array errors; guard the loop
  if [ "${#stale[@]}" -gt 0 ]; then
    for rel in "${stale[@]}"; do
      rm "$dest/$rel"
      echo "clean $dest/$rel (stale deploy)"
    done
  fi
  return 0
}

# Rebuild a tree's ledger from what is now installed — the deployed
# tree itself is the truth, so this is a full rewrite, not a merge.
record_tree() {  # <dest-dir>
  local d="$1" tmp="$d/$LEDGER_NAME.tmp"
  : > "$tmp"
  while IFS= read -r rel; do
    rel="${rel#./}"; [ -n "$rel" ] || continue
    printf '%s %s\n' "$(sha "$d/$rel")" "$rel" >> "$tmp"
  done < <(cd "$d" && find . -type f ! -name '.DS_Store' \
      ! -path '*/__pycache__/*' ! -name "$LEDGER_NAME*" | sort)
  mv "$tmp" "$d/$LEDGER_NAME"
}

SKILLS=()
for d in "$PKG_ROOT"/skills/*/; do
  [ -f "${d}SKILL.md" ] || continue
  SKILLS+=("$(basename "$d")")
done

install_skill_tree() {  # <skill-dir> <dest-root> — refuses on foreign files
  local master="$1" dest="$2/$(basename "$1")" rel
  sweep_tree "$master" "$dest" "$dest/$LEDGER_NAME" || return 1
  mkdir -p "$dest"
  # Per-file atomic replacement, not a tree copy: each destination file
  # lands whole or not at all (FR-007); identical files stay untouched.
  while IFS= read -r rel; do
    rel="${rel#./}"; [ -n "$rel" ] || continue
    mkdir -p "$dest/$(dirname "$rel")"
    cmp -s "$master/$rel" "$dest/$rel" \
      || atomic_put "$master/$rel" "$dest/$rel" || return 1
  done < <(cd "$master" && find . -type f ! -name '.DS_Store' \
      ! -path '*/__pycache__/*' ! -name "$LEDGER_NAME*")
  record_tree "$dest"
}

install_command() {  # <master-file> <base> <root> — ledger-guarded copy
  local f="$1" base="$2" root="$3"
  # Second statement, deliberately: in one `local a=$b c=$a` line every
  # expansion happens BEFORE any assignment, so $root would read the
  # caller's leftover global, not this function's parameter.
  local dest="$root/$base.md" ledger="$root/$LEDGER_NAME"
  mkdir -p "$root"
  if [ -e "$dest" ] && ! cmp -s "$f" "$dest" \
     && ! ledger_entry_matches "$ledger" "$base" "$dest"; then
    echo "REFUSE $dest — foreign file (differs from master, not a prior deploy); resolve manually"
    return 1
  fi
  atomic_put "$f" "$dest" || return 1
  ledger_record "$ledger" "$base" "$f"
}

# --- preflight -------------------------------------------------------------
# Plan every destination this run may touch BEFORE the first write
# (FR-001, FR-002): tools/ownership.py classifies each candidate as
# create / update / unchanged / delete / refuse from the destination's
# provenance ledger, and generated content is rendered to scratch first
# so a generator or source failure also costs zero writes (D-002 — a
# collision in the last root must not leave the first root
# half-updated). Refuse means the ledger cannot prove the occupant is a
# prior deploy: however identical it looks, it is never adopted.
# Unplanned here: agy personas (committed regenerate-only repo
# artifacts, no destination ledger) and the opencode/droid agent roots
# (no provenance record exists yet; their deployment alignment is
# T006's) — but their renders are still validated before any write.
PREFLIGHT_FAIL=0
preflight_stage="$(mktemp -d)"
trap 'rm -rf "$preflight_stage"' EXIT

plan_tree_root() {  # <src-dir> <dest-dir> — fail the run on any refusal
  local dest="$2" out rc line
  out="$(python3 "$PKG_ROOT/tools/ownership.py" plan-tree \
      --src "$1" --dest "$dest")" && rc=0 || rc=$?
  # rc 2 is a planner validation error (missing source, corrupt ledger)
  # — a prerequisite failure, loud on stderr, fatal here either way.
  if [ "$rc" -eq 2 ]; then PREFLIGHT_FAIL=1; return 0; fi
  while IFS= read -r line; do
    case "$line" in
      refuse\ *)
        PREFLIGHT_FAIL=1
        echo "REFUSE $dest/${line#refuse } — foreign file (differs from master, not a prior deploy); resolve manually" ;;
      *)
        # --dry-run reports every decision in the planner's own
        # create/update/unchanged/delete vocabulary (FR-009)
        [ "$DRY_RUN" = 1 ] && echo "plan  ${line%% *} $dest/${line#* }" ;;
    esac
  done <<< "$out"
  return 0
}

plan_file_dest() {  # <src-file> <dest-file> [planner args...] — same contract
  local src="$1" dest="$2" out rc
  shift 2
  out="$(python3 "$PKG_ROOT/tools/ownership.py" plan-file \
      --src "$src" --dest "$dest" "$@")" && rc=0 || rc=$?
  if [ "$rc" -eq 2 ]; then PREFLIGHT_FAIL=1; return 0; fi
  case "$out" in
    refuse\ *)
      PREFLIGHT_FAIL=1
      echo "REFUSE $dest — foreign file (differs from master, not a prior deploy); resolve manually" ;;
    *)
      [ "$DRY_RUN" = 1 ] && echo "plan  ${out%% *} $dest" ;;
  esac
  return 0
}

for name in "${SKILLS[@]}"; do
  skill_dir="$PKG_ROOT/skills/$name"

  for root in "${SKILLS_ROOTS[@]}"; do
    plan_tree_root "$skill_dir" "$root/$name"
  done

  # Allowlisted command sources validated before any root is planned.
  cmd_bases=()
  if [ -d "$skill_dir/commands" ]; then
    for base in $name $(extra_commands "$name"); do
      if [ -f "$skill_dir/commands/$base.md" ]; then
        cmd_bases+=("$base")
      else
        echo "MISSING skills/$name/commands/$base.md (allowlisted, absent)"
        PREFLIGHT_FAIL=1
      fi
    done
  fi
  if [ "${#cmd_bases[@]}" -gt 0 ]; then
    for base in "${cmd_bases[@]}"; do
      f="$skill_dir/commands/$base.md"
      for root in "${COMMANDS_ROOTS[@]}"; do
        plan_file_dest "$f" "$root/$base.md" --name "$base"
      done
      if [ -d "$HOME/.factory" ]; then
        plan_file_dest "$f" "$DROID_COMMANDS_ROOT/$base.md" --name "$base"
      fi
    done
  fi

  if [ -d "$skill_dir/agents" ]; then
    # Validate all generated content up front: render every dialect to
    # scratch, gated exactly like the install blocks below (defs land
    # only where the harness home already exists).
    python3 "$PKG_ROOT/tools/omp-defs.py" --skill-dir "$skill_dir" \
      --out "$preflight_stage/$name/omp" || PREFLIGHT_FAIL=1
    python3 "$PKG_ROOT/tools/agent-defs.py" --target agy \
      --skill-dir "$skill_dir" --out "$preflight_stage/$name/agy" || PREFLIGHT_FAIL=1
    if [ -d "$HOME/.config/opencode" ]; then
      python3 "$PKG_ROOT/tools/agent-defs.py" --target opencode \
        --skill-dir "$skill_dir" --out "$preflight_stage/$name/opencode" || PREFLIGHT_FAIL=1
      # Optional-harness agent roots plan like every other destination:
      # the generator's own write-gate at apply time is the last resort,
      # never the plan (a foreign collision here must fail before the
      # first write anywhere).
      for f in "$preflight_stage/$name/opencode"/*.md; do
        [ -e "$f" ] || continue
        plan_file_dest "$f" "$OPENCODE_AGENTS_ROOT/$(basename "$f")"
      done
    fi
    if [ -d "$HOME/.factory" ]; then
      python3 "$PKG_ROOT/tools/agent-defs.py" --target droid \
        --skill-dir "$skill_dir" --out "$preflight_stage/$name/droid" || PREFLIGHT_FAIL=1
      for f in "$preflight_stage/$name/droid"/*.md; do
        [ -e "$f" ] || continue
        plan_file_dest "$f" "$DROID_AGENTS_ROOT/$(basename "$f")"
      done
    fi

    # Claude agents: plain copies under the agents root's own ledger.
    for f in "$skill_dir"/agents/*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      [[ "$base" == _* ]] && continue
      plan_file_dest "$f" "$CLAUDE_AGENTS_ROOT/$base"
    done

    # omp defs: the generator's per-skill manifest IS this skill's
    # provenance in the shared root, so it is the plan's ledger.
    for f in "$preflight_stage/$name/omp"/*.md; do
      [ -e "$f" ] || continue
      plan_file_dest "$f" "$OMP_AGENTS_ROOT/$(basename "$f")" \
        --ledger "$OMP_AGENTS_ROOT/.spec-dev-kit-omp-defs-$name"
    done
  fi

  # Workflow dialects: bake each master against the skill copy the
  # install step will create (the bake is a pure text transform, so the
  # copy need not exist yet) and plan the harness's workflow root.
  if [ -d "$skill_dir/workflows" ]; then
    for wf in "$skill_dir"/workflows/*; do
      [ -f "$wf" ] || continue
      case "$wf" in
        *.dwf.ts) wf_h=zcode ;;
        *.js)     wf_h=claude ;;
        *) continue ;;  # unknown extensions: install-workflow.sh notes them
      esac
      if [ -d "$HOME/.$wf_h" ]; then
        expected="$preflight_stage/$name-wf-$(basename "$wf")"
        python3 "$PKG_ROOT/tools/workflow-defs.py" --bake "$wf" \
            --skill-dir "$HOME/.$wf_h/skills/$name" > "$expected" \
            || { PREFLIGHT_FAIL=1; continue; }
        plan_file_dest "$expected" "$HOME/.$wf_h/workflows/$(basename "$wf")"
      fi
    done
  fi
done

if [ "$PREFLIGHT_FAIL" -ne 0 ]; then
  echo "PREFLIGHT FAILED — nothing was written; resolve the refusals above and rerun"
  exit 1
fi

if [ "$DRY_RUN" = 1 ]; then
  echo "dry run complete — nothing was written, no ownership recorded"
  exit 0
fi

# --- apply -----------------------------------------------------------------
# --check stops here (FR-009): the preflight above reported refusals and
# the verify pass below reports drift — read-only either way.
if [ "$CHECK" = 0 ]; then
  for name in "${SKILLS[@]}"; do
    skill_dir="$PKG_ROOT/skills/$name"

    for root in "${SKILLS_ROOTS[@]}"; do
      install_skill_tree "$skill_dir" "$root" || fail=1
    done

    if [ -d "$skill_dir/commands" ]; then
      for base in $name $(extra_commands "$name"); do
        f="$skill_dir/commands/$base.md"
        rel="skills/$name/commands/$base.md"
        if [ ! -f "$f" ]; then
          echo "MISSING $rel (allowlisted, absent)"; fail=1; continue
        fi
        for root in "${COMMANDS_ROOTS[@]}"; do
          install_command "$f" "$base" "$root" || fail=1
        done
      done
    fi

    # Factory Droid's own command root — gated on the harness's config
    # home existing, like the opencode/droid agent defs above: sync never
    # fabricates a harness directory; installing the harness just needs
    # one more sync run. Same provenance-ledger discipline, kept as a
    # separate block so the shared roots' path is untouched (D-017).
    if [ -d "$HOME/.factory" ]; then
      for base in $name $(extra_commands "$name"); do
        f="$skill_dir/commands/$base.md"
        if [ ! -f "$f" ]; then
          echo "MISSING skills/$name/commands/$base.md (allowlisted, absent)"; fail=1; continue
        fi
        install_command "$f" "$base" "$DROID_COMMANDS_ROOT" || fail=1
      done
    else
      echo "skip  droid commands — ~/.factory absent (harness not installed)"
    fi

    # Dynamic workflows (ADR-019): each dialect file under
    # skills/<name>/workflows/ installs into its own harness's workflow
    # root via the dedicated installer, which bakes that root's own skill
    # copy as skill_dir (and refuses foreign destinations per the same
    # ledger discipline). Gated on the harness home existing — user roots
    # are never fabricated here either.
    if [ -d "$skill_dir/workflows" ]; then
      for wf_h in zcode claude; do
        if [ -d "$HOME/.$wf_h" ]; then
          bash "$PKG_ROOT/tools/install-workflow.sh" "$wf_h" \
            --skill-dir "$HOME/.$wf_h/skills/$name" || fail=1
        else
          echo "skip  $wf_h workflows — ~/.$wf_h absent (harness not installed)"
        fi
      done
    fi

    if [ -d "$skill_dir/agents" ]; then
      mkdir -p "$CLAUDE_AGENTS_ROOT"
      agents_ledger="$CLAUDE_AGENTS_ROOT/$LEDGER_NAME"
      for f in "$skill_dir"/agents/*.md; do
        base="$(basename "$f")"
        [[ "$base" == _* ]] && continue
        dest="$CLAUDE_AGENTS_ROOT/$base"
        if [ -e "$dest" ] && ! cmp -s "$f" "$dest" \
           && ! ledger_entry_matches "$agents_ledger" "$base" "$dest"; then
          echo "REFUSE $dest — foreign file (differs from master, not a prior deploy); resolve manually"
          fail=1; continue
        fi
        atomic_put "$f" "$dest" || { fail=1; continue; }
        ledger_record "$agents_ledger" "$base" "$f"
      done
      mkdir -p "$OMP_AGENTS_ROOT"
      python3 "$PKG_ROOT/tools/omp-defs.py" --skill-dir "$skill_dir" --out "$OMP_AGENTS_ROOT"

      # Optional harnesses: agent defs land only where the harness's own
      # config home already exists — a fresh harness install just needs
      # one more sync run. Skills for both flow through the
      # ~/.agents/skills compatibility root each already scans.
      if [ -d "$HOME/.config/opencode" ]; then
        mkdir -p "$OPENCODE_AGENTS_ROOT"
        python3 "$PKG_ROOT/tools/agent-defs.py" --target opencode --skill-dir "$skill_dir" --out "$OPENCODE_AGENTS_ROOT"
      else
        echo "skip  opencode defs — ~/.config/opencode absent (harness not installed)"
      fi
      if [ -d "$HOME/.factory" ]; then
        mkdir -p "$DROID_AGENTS_ROOT"
        python3 "$PKG_ROOT/tools/agent-defs.py" --target droid --skill-dir "$skill_dir" --out "$DROID_AGENTS_ROOT"
      else
        echo "skip  droid defs — ~/.factory absent (harness not installed)"
      fi

      # Antigravity (agy) consumes this REPO as a plugin (root plugin.json;
      # `agy plugin install <repo>` owns ~/.gemini/config/plugins) — sync
      # never writes there. The root agents/ personas it registers are a
      # committed, regenerate-only artifact of the briefs.
      python3 "$PKG_ROOT/tools/agent-defs.py" --target agy --skill-dir "$skill_dir" --out "$PKG_ROOT/agents" >/dev/null
    fi
  done
fi

# --- verify ---------------------------------------------------------------

verify_tree() {  # <master> <copy> <label>
  local master="$1" copy="$2" label="$3" m c
  if [ ! -d "$copy" ]; then
    # --check on a destination nothing ever installed (FR-009)
    echo "MISSING $label — not installed"; fail=1
    return 0
  fi
  m="$(cd "$master" && find . -type f ! -name .DS_Store ! -path '*/__pycache__/*' ! -name '.spec-dev-kit-deployed*' -exec shasum -a 256 {} + | sort -k2)"
  c="$(cd "$copy" && find . -type f ! -name .DS_Store ! -path '*/__pycache__/*' ! -name '.spec-dev-kit-deployed*' -exec shasum -a 256 {} + | sort -k2)"
  if [[ "$m" == "$c" ]]; then
    echo "OK  $label — identical ($(printf '%s\n' "$m" | wc -l | tr -d ' ') files)"
  else
    echo "DRIFT $label"
    diff <(printf '%s\n' "$m") <(printf '%s\n' "$c") || true
    fail=1
  fi
}

verify_command() {  # <master-file> <base> <root>
  if [ ! -e "$3/$2.md" ]; then
    echo "MISSING $3/$2.md"; fail=1
  elif cmp -s "$1" "$3/$2.md"; then
    echo "OK  $3/$2.md"
  else
    echo "DRIFT $3/$2.md"; fail=1
  fi
}

for name in "${SKILLS[@]}"; do
  skill_dir="$PKG_ROOT/skills/$name"

  # SKILL.md frontmatter version must equal the VERSION file — nothing
  # else enforces the pair, and they have drifted twice already.
  v_file="$(cat "$skill_dir/VERSION" 2>/dev/null || true)"
  v_fm="$(sed -n 's/^  version: "\(.*\)"$/\1/p' "$skill_dir/SKILL.md" | head -1)"
  if [ -n "$v_file" ] && [ "$v_file" != "$v_fm" ]; then
    echo "DRIFT $name version — VERSION=$v_file but SKILL.md says $v_fm"
    fail=1
  fi

  # zcode/claude skill loaders reject a SKILL.md description over 1024
  # chars — the skill silently fails to register (seen twice on
  # spec-to-prod). Same shape as the version pairing above: mechanical
  # guard on every sync run.
  d_len="$(python3 -c 'import re,sys; t=open(sys.argv[1]).read(); m=re.search(r"description: >-\n((?:  .*\n|\n)*?)metadata:", t); print(len("".join(l[2:] if l.startswith("  ") else l for l in m.group(1).splitlines(keepends=True)).strip()) if m else 0)' "$skill_dir/SKILL.md")"
  if [ "${d_len:-0}" -gt 1024 ]; then
    echo "DRIFT $name description — ${d_len} chars exceeds the 1024-char loader limit"
    fail=1
  fi

  for root in "${SKILLS_ROOTS[@]}"; do
    verify_tree "$skill_dir" "$root/$name" "$root/$name"
  done

  if [ -d "$skill_dir/commands" ]; then
    for base in $name $(extra_commands "$name"); do
      f="$skill_dir/commands/$base.md"
      [ -f "$f" ] || { echo "MISSING $f (allowlisted)"; fail=1; continue; }
      for root in "${COMMANDS_ROOTS[@]}"; do
        verify_command "$f" "$base" "$root"
      done
      if [ -d "$HOME/.factory" ]; then
        verify_command "$f" "$base" "$DROID_COMMANDS_ROOT"
      fi
    done
  fi

  # Dynamic-workflow verify (mirror of the install block above): the
  # installed copies must match a fresh bake at the same skill_dir.
  if [ -d "$skill_dir/workflows" ]; then
    for wf_h in zcode claude; do
      if [ -d "$HOME/.$wf_h" ]; then
        bash "$PKG_ROOT/tools/install-workflow.sh" "$wf_h" \
          --skill-dir "$HOME/.$wf_h/skills/$name" --check || fail=1
      fi
    done
  fi

  if [ -d "$skill_dir/agents" ]; then
    for f in "$skill_dir"/agents/*.md; do
      base="$(basename "$f")"
      [[ "$base" == _* ]] && continue
      if cmp -s "$f" "$CLAUDE_AGENTS_ROOT/$base"; then
        echo "OK  def $base"
      else
        echo "DRIFT def $base"; fail=1
      fi
    done

    # ~/.omp/agent/agents is a shared root (omp agent unpacks, other
    # skills' own roles, hand-added defs) — verify per this skill's own
    # generated file, never the whole directory. Regenerate fresh into a
    # scratch dir and diff content only: the stale-removal invariant
    # itself (an old/renamed role never lingers) is covered by
    # tools/tests/test_omp_defs.py against omp-defs.py directly, run on
    # a scratch dir rather than the live shared one.
    tmp="$(mktemp -d)"
    python3 "$PKG_ROOT/tools/omp-defs.py" --skill-dir "$skill_dir" --out "$tmp" >/dev/null
    for f in "$tmp"/*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      if cmp -s "$f" "$OMP_AGENTS_ROOT/$base"; then
        echo "OK  omp def $base"
      else
        echo "DRIFT omp def $base"; fail=1
      fi
    done

    # opencode/droid defs (optional harnesses): regenerate to scratch,
    # compare only where the harness root exists — mirrors install.
    for spec in "opencode:$OPENCODE_AGENTS_ROOT" "droid:$DROID_AGENTS_ROOT"; do
      tgt="${spec%%:*}"; aroot="${spec#*:}"
      if [ -d "$aroot" ]; then
        t2="$(mktemp -d)"
        python3 "$PKG_ROOT/tools/agent-defs.py" --target "$tgt" --skill-dir "$skill_dir" --out "$t2" >/dev/null
        ok=0
        for f in "$t2"/*.md; do
          [ -e "$f" ] || continue
          if cmp -s "$f" "$aroot/$(basename "$f")"; then
            ok=$((ok + 1))
          else
            echo "DRIFT $tgt def $(basename "$f")"; fail=1
          fi
        done
        [ "$ok" -gt 0 ] && echo "OK  $tgt defs ($ok)"
        rm -rf "$t2"
      fi
    done

    # agy personas: the committed repo-root agents/ must match a fresh
    # regeneration byte-for-byte.
    t3="$(mktemp -d)"
    python3 "$PKG_ROOT/tools/agent-defs.py" --target agy --skill-dir "$skill_dir" --out "$t3" >/dev/null
    for f in "$t3"/*.md; do
      base="$(basename "$f")"
      if cmp -s "$f" "$PKG_ROOT/agents/$base"; then
        echo "OK  agy def $base"
      else
        echo "DRIFT agy def $base (rerun sync)"; fail=1
      fi
    done
    rm -rf "$t3"
    rm -rf "$tmp"
  fi
done

exit $fail
