#!/usr/bin/env bash
# Sync every skill in this repo (master source) to every install root,
# then SHA-verify the result.
#
# Topology — N skills (skills/<name>/) x the harness roots below:
#   skills/<name>/            -> ~/.agents/skills/<name>/
#                              -> ~/.claude/skills/<name>/
#                              -> ~/.zcode/skills/<name>/
#                              -> ~/.omp/agent/skills/<name>/
#                                 (omp-native root, priority-100 provider
#                                 — omp sessions load this copy)
#   skills/<name>/commands/<name>.md -> ~/.agents/commands/,
#                              ~/.claude/commands/, ~/.zcode/commands/
#                              — plus the bare names the skill opts into
#                              via its own commands/extra.txt (generic
#                              names in shared roots are an explicit
#                              per-skill opt-in, never a glob; a foreign
#                              file at any destination is refused, not
#                              clobbered; omp needs none —
#                              /skill:<name> auto-registers)
#   skills/<name>/agents/*.md -> ~/.claude/agents/ (as-is; the harness
#                                 reads Claude-style frontmatter directly)
#                              -> ~/.omp/agent/agents/ (regenerated with
#                                 omp frontmatter by tools/omp-defs.py —
#                                 omp skips ~/.claude/agents and its tool
#                                 registry is lowercase). Files named with
#                                 a leading underscore (shared prose, e.g.
#                                 _shared-protocol.md) are not roles and
#                                 are skipped. zcode gets no agents/
#                                 install step: SKILL.md § Spawn mechanics
#                                 documents it as having no
#                                 user-installable agent types, so it
#                                 only gets skills/ + commands/.
#                              -> ~/.config/opencode/agents/ and
#                                 ~/.factory/droids/ (OPTIONAL roots,
#                                 regenerated by tools/agent-defs.py:
#                                 opencode subagents / Factory droids).
#                                 Installed only when the harness's own
#                                 config home exists — sync never
#                                 fabricates a harness directory. Both
#                                 harnesses read skills from the
#                                 ~/.agents/skills compatibility root
#                                 already installed above.
#                              -> <repo>/agents/ (agy personas — COMMITTED
#                                 regenerate-only copies of the briefs:
#                                 the repo root is the plugin that
#                                 `agy plugin install` copies; agy owns
#                                 ~/.gemini/config/plugins itself).
#
# omp also reads ~/.agents/skills (its `agents` provider, priority 70),
# so that root alone would serve omp sessions; the ~/.omp copy makes
# every skill self-sufficient inside omp and wins omp's same-name dedup.
#
# A skill opts into this topology just by existing at skills/<name>/ with
# a SKILL.md — no registration step, no list to edit here.
#
# Run from anywhere: tools/sync.sh — edits always land in skills/<name>/
# first; this script is the only thing that copies out.
set -euo pipefail

PKG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail=0

SKILLS_ROOTS=(
  "$HOME/.agents/skills"
  "$HOME/.claude/skills"
  "$HOME/.zcode/skills"
  "$HOME/.omp/agent/skills"
)
COMMANDS_ROOTS=(
  "$HOME/.agents/commands"
  "$HOME/.claude/commands"
  "$HOME/.zcode/commands"
)
CLAUDE_AGENTS_ROOT="$HOME/.claude/agents"
OMP_AGENTS_ROOT="$HOME/.omp/agent/agents"
# Optional harness agent-def roots — active only when the harness's own
# config home exists (see the install loop).
OPENCODE_AGENTS_ROOT="$HOME/.config/opencode/agents"
DROID_AGENTS_ROOT="$HOME/.factory/droids"

# Bare-named commands a skill ships beyond its collision-proof
# <name>.md router: an explicit `commands/extra.txt` in the skill (one
# line, space-separated bare names — a reviewed file inside the skill
# dir, never a glob; ADR-013). Generic names (spec.md, plan.md, ...)
# land flat in shared global command roots, so the opt-in lives with
# the skill that pays for it, and a second skill wanting the same bare
# name is a rename-or-namespace decision.
extra_commands() {  # <skill-name> -> bare names on stdout
  local f="$PKG_ROOT/skills/$1/commands/extra.txt"
  if [ -f "$f" ]; then cat "$f"; fi
}

# Provenance ledger: every command root keeps the sha256 of each file
# this script deployed there (.spec-dev-kit-deployed — harnesses read
# only *.md, so the hidden file is inert). A destination that differs
# from the master is overwritten ONLY when its hash sits in the ledger
# (a previous deploy of ours, committed or not); anything else at the
# destination is foreign — refuse loudly, never clobber.
ledger_entry_matches() {  # <ledger-file> <command-name> <dest-file>
  [ -f "$1" ] || return 1
  local want
  want="$(shasum -a 256 < "$3" | cut -d' ' -f1)"
  awk -v n="$2" -v h="$want" '$1 == h && $2 == n {found = 1}
        END {exit found ? 0 : 1}' "$1"
}

ledger_record() {  # <ledger-file> <command-name> <master-file>
  local h
  h="$(shasum -a 256 < "$3" | cut -d' ' -f1)"
  touch "$1"
  grep -v " $2\$" "$1" > "$1.tmp" || true
  printf '%s %s\n' "$h" "$2" >> "$1.tmp"
  mv "$1.tmp" "$1"
}

sha() {  # <file> -> sha256 on stdout
  shasum -a 256 < "$1" | cut -d' ' -f1
}

LEDGER_NAME=".spec-dev-kit-deployed"

# Skills-tree provenance — the command roots' refuse-don't-clobber
# rule, applied to a whole installed directory. A dest file the master
# no longer ships is either stale-own (its hash sits in the tree's
# ledger — a previous deploy of ours; deleted) or foreign (not in the
# ledger; REFUSED loudly, the tree is left untouched). Returns 1 when
# anything foreign was found.
sweep_tree() {  # <master-dir> <dest-dir> <ledger>
  local master="$1" dest="$2" ledger="$3" rel bad=0
  [ -d "$dest" ] || return 0
  while IFS= read -r rel; do
    rel="${rel#./}"; [ -n "$rel" ] || continue
    if [ -f "$master/$rel" ]; then continue; fi
    if [ -f "$ledger" ] && awk -v h="$(sha "$dest/$rel")" -v n="$rel" \
        '$1 == h && $2 == n {found = 1} END {exit found ? 0 : 1}' "$ledger"; then
      rm "$dest/$rel"
      echo "clean $dest/$rel (stale deploy)"
    else
      echo "REFUSE $dest/$rel — foreign file (not shipped by the skill, not a prior deploy); resolve manually"
      bad=1
    fi
  done < <(cd "$dest" && find . -type f ! -name '.DS_Store' \
      ! -path '*/__pycache__/*' ! -name "$LEDGER_NAME*")
  return "$bad"
}

# Rebuild a tree's ledger from what is now installed — the deployed
# tree itself is the truth, so this is a full rewrite, not a merge.
record_tree() {  # <dest-dir>
  local d="$1" tmp="$d/$LEDGER_NAME.tmp"
  : > "$tmp"
  while IFS= read -r rel; do
    rel="${rel#./}"; [ -n "$rel" ] || continue
    printf '%s %s\n' "$(sha "$d/$rel")" "$rel" >> "$tmp"
  done < <(cd "$d" && find . -type f ! -name '.DS_Store' \
      ! -path '*/__pycache__/*' ! -name "$LEDGER_NAME*" | sort)
  mv "$tmp" "$d/$LEDGER_NAME"
}

SKILLS=()
for d in "$PKG_ROOT"/skills/*/; do
  [ -f "${d}SKILL.md" ] || continue
  SKILLS+=("$(basename "$d")")
done

install_skill_tree() {  # <skill-dir> <dest-root> — refuses on foreign files
  local dest="$2/$(basename "$1")"
  sweep_tree "$1" "$dest" "$dest/$LEDGER_NAME" || return 1
  mkdir -p "$dest"
  rsync -a --exclude '.DS_Store' --exclude '__pycache__/' \
    --exclude "$LEDGER_NAME*" "$1/" "$dest/"
  record_tree "$dest"
}

for name in "${SKILLS[@]}"; do
  skill_dir="$PKG_ROOT/skills/$name"

  for root in "${SKILLS_ROOTS[@]}"; do
    install_skill_tree "$skill_dir" "$root" || fail=1
  done

  if [ -d "$skill_dir/commands" ]; then
    for base in $name $(extra_commands "$name"); do
      f="$skill_dir/commands/$base.md"
      rel="skills/$name/commands/$base.md"
      if [ ! -f "$f" ]; then
        echo "MISSING $rel (allowlisted, absent)"; fail=1; continue
      fi
      for root in "${COMMANDS_ROOTS[@]}"; do
        mkdir -p "$root"
        dest="$root/$base.md"
        ledger="$root/.spec-dev-kit-deployed"
        if [ -e "$dest" ] && ! cmp -s "$f" "$dest" \
           && ! ledger_entry_matches "$ledger" "$base" "$dest"; then
          echo "REFUSE $dest — foreign file (differs from master, not a prior deploy); resolve manually"
          fail=1; continue
        fi
        cp "$f" "$dest"
        ledger_record "$ledger" "$base" "$f"
      done
    done
  fi

  if [ -d "$skill_dir/agents" ]; then
    mkdir -p "$CLAUDE_AGENTS_ROOT"
    agents_ledger="$CLAUDE_AGENTS_ROOT/$LEDGER_NAME"
    for f in "$skill_dir"/agents/*.md; do
      base="$(basename "$f")"
      [[ "$base" == _* ]] && continue
      dest="$CLAUDE_AGENTS_ROOT/$base"
      if [ -e "$dest" ] && ! cmp -s "$f" "$dest" \
         && ! ledger_entry_matches "$agents_ledger" "$base" "$dest"; then
        echo "REFUSE $dest — foreign file (differs from master, not a prior deploy); resolve manually"
        fail=1; continue
      fi
      cp "$f" "$dest"
      ledger_record "$agents_ledger" "$base" "$f"
    done
    mkdir -p "$OMP_AGENTS_ROOT"
    python3 "$PKG_ROOT/tools/omp-defs.py" --skill-dir "$skill_dir" --out "$OMP_AGENTS_ROOT"

    # Optional harnesses: agent defs land only where the harness's own
    # config home already exists — a fresh harness install just needs
    # one more sync run. Skills for both flow through the
    # ~/.agents/skills compatibility root each already scans.
    if [ -d "$HOME/.config/opencode" ]; then
      mkdir -p "$OPENCODE_AGENTS_ROOT"
      python3 "$PKG_ROOT/tools/agent-defs.py" --target opencode --skill-dir "$skill_dir" --out "$OPENCODE_AGENTS_ROOT"
    else
      echo "skip  opencode defs — ~/.config/opencode absent (harness not installed)"
    fi
    if [ -d "$HOME/.factory" ]; then
      mkdir -p "$DROID_AGENTS_ROOT"
      python3 "$PKG_ROOT/tools/agent-defs.py" --target droid --skill-dir "$skill_dir" --out "$DROID_AGENTS_ROOT"
    else
      echo "skip  droid defs — ~/.factory absent (harness not installed)"
    fi

    # Antigravity (agy) consumes this REPO as a plugin (root plugin.json;
    # `agy plugin install <repo>` owns ~/.gemini/config/plugins) — sync
    # never writes there. The root agents/ personas it registers are a
    # committed, regenerate-only artifact of the briefs.
    python3 "$PKG_ROOT/tools/agent-defs.py" --target agy --skill-dir "$skill_dir" --out "$PKG_ROOT/agents" >/dev/null
  fi
done

# --- verify ---------------------------------------------------------------

verify_tree() {  # <master> <copy> <label>
  local master="$1" copy="$2" label="$3" m c
  m="$(cd "$master" && find . -type f ! -name .DS_Store ! -path '*/__pycache__/*' ! -name '.spec-dev-kit-deployed*' -exec shasum -a 256 {} + | sort -k2)"
  c="$(cd "$copy" && find . -type f ! -name .DS_Store ! -path '*/__pycache__/*' ! -name '.spec-dev-kit-deployed*' -exec shasum -a 256 {} + | sort -k2)"
  if [[ "$m" == "$c" ]]; then
    echo "OK  $label — identical ($(printf '%s\n' "$m" | wc -l | tr -d ' ') files)"
  else
    echo "DRIFT $label"
    diff <(printf '%s\n' "$m") <(printf '%s\n' "$c") || true
    fail=1
  fi
}

for name in "${SKILLS[@]}"; do
  skill_dir="$PKG_ROOT/skills/$name"

  # SKILL.md frontmatter version must equal the VERSION file — nothing
  # else enforces the pair, and they have drifted twice already.
  v_file="$(cat "$skill_dir/VERSION" 2>/dev/null || true)"
  v_fm="$(sed -n 's/^  version: "\(.*\)"$/\1/p' "$skill_dir/SKILL.md" | head -1)"
  if [ -n "$v_file" ] && [ "$v_file" != "$v_fm" ]; then
    echo "DRIFT $name version — VERSION=$v_file but SKILL.md says $v_fm"
    fail=1
  fi

  for root in "${SKILLS_ROOTS[@]}"; do
    verify_tree "$skill_dir" "$root/$name" "$root/$name"
  done

  if [ -d "$skill_dir/commands" ]; then
    for base in $name $(extra_commands "$name"); do
      f="$skill_dir/commands/$base.md"
      [ -f "$f" ] || { echo "MISSING $f (allowlisted)"; fail=1; continue; }
      for root in "${COMMANDS_ROOTS[@]}"; do
        if cmp -s "$f" "$root/$base.md"; then
          echo "OK  $root/$base.md"
        else
          echo "DRIFT $root/$base.md"; fail=1
        fi
      done
    done
  fi

  if [ -d "$skill_dir/agents" ]; then
    for f in "$skill_dir"/agents/*.md; do
      base="$(basename "$f")"
      [[ "$base" == _* ]] && continue
      if cmp -s "$f" "$CLAUDE_AGENTS_ROOT/$base"; then
        echo "OK  def $base"
      else
        echo "DRIFT def $base"; fail=1
      fi
    done

    # ~/.omp/agent/agents is a shared root (omp agent unpacks, other
    # skills' own roles, hand-added defs) — verify per this skill's own
    # generated file, never the whole directory. Regenerate fresh into a
    # scratch dir and diff content only: the stale-removal invariant
    # itself (an old/renamed role never lingers) is covered by
    # tools/tests/test_omp_defs.py against omp-defs.py directly, run on
    # a scratch dir rather than the live shared one.
    tmp="$(mktemp -d)"
    python3 "$PKG_ROOT/tools/omp-defs.py" --skill-dir "$skill_dir" --out "$tmp" >/dev/null
    for f in "$tmp"/*.md; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      if cmp -s "$f" "$OMP_AGENTS_ROOT/$base"; then
        echo "OK  omp def $base"
      else
        echo "DRIFT omp def $base"; fail=1
      fi
    done

    # opencode/droid defs (optional harnesses): regenerate to scratch,
    # compare only where the harness root exists — mirrors install.
    for spec in "opencode:$OPENCODE_AGENTS_ROOT" "droid:$DROID_AGENTS_ROOT"; do
      tgt="${spec%%:*}"; aroot="${spec#*:}"
      if [ -d "$aroot" ]; then
        t2="$(mktemp -d)"
        python3 "$PKG_ROOT/tools/agent-defs.py" --target "$tgt" --skill-dir "$skill_dir" --out "$t2" >/dev/null
        ok=0
        for f in "$t2"/*.md; do
          [ -e "$f" ] || continue
          if cmp -s "$f" "$aroot/$(basename "$f")"; then
            ok=$((ok + 1))
          else
            echo "DRIFT $tgt def $(basename "$f")"; fail=1
          fi
        done
        [ "$ok" -gt 0 ] && echo "OK  $tgt defs ($ok)"
        rm -rf "$t2"
      fi
    done

    # agy personas: the committed repo-root agents/ must match a fresh
    # regeneration byte-for-byte.
    t3="$(mktemp -d)"
    python3 "$PKG_ROOT/tools/agent-defs.py" --target agy --skill-dir "$skill_dir" --out "$t3" >/dev/null
    for f in "$t3"/*.md; do
      base="$(basename "$f")"
      if cmp -s "$f" "$PKG_ROOT/agents/$base"; then
        echo "OK  agy def $base"
      else
        echo "DRIFT agy def $base (rerun sync)"; fail=1
      fi
    done
    rm -rf "$t3"
    rm -rf "$tmp"
  fi
done

exit $fail
