#!/usr/bin/env python3
"""Generate dynamic-workflow dialects from one loop-contract definition.

The spec-to-prod frontier loop ("compute the ready wave from doc state,
spawn it, recompute" — graph.py --run's own shape) has two native
workflow-runtime instantiations today, and this tool emits both as
committed, regenerate-only artifacts under the skill's workflows/ dir:

  spec-run.dwf.ts  — zcode dynamic workflows: TypeScript against the
                     zcode facade (typed agent().ask<T>(), literal
                     phase() names, world.run invocations, a published
                     markdown run summary). No import/export/declare
                     token anywhere in the file — the facade compiles a
                     plain function body.
  spec-run.js      — Claude Code dynamic workflows: plain JavaScript
                     with `export const meta` as the first statement,
                     agent(prompt, {label, schema}) / pipeline / phase /
                     log primitives, and no direct filesystem or shell
                     access in the script itself (a one-shot probe agent
                     runs graph.py and returns its stdout verbatim).

Neither dialect re-implements a single readiness rule: graph.py's
--state-json is the only oracle both parse, --emit-spawns writes the
payloads both spawn, and the human-gate pause set mirrors graph.py's
find_pause exactly (clarify, an undetermined research-gate, before-audit,
approve, the closing-audit judgment, tick-commit — never auto-satisfied;
the run stops AWAITING HUMAN and a later rerun resumes from doc state).
Stop conditions mirror graph.py --run: a gate, workflow completion, a
held frontier, the wave cap (default 12), or a wave that changed no doc
state. The two templates below are the single representation (ADR-019 /
tech-spec D-006): never hand-edit the generated files; edit the template
constants here and regenerate.

The masters carry a literal __SKILL_DIR__ placeholder.
tools/install-workflow.sh bakes each harness root's own skill copy into
the installed file (and a runtime skill_dir arg wins over the bake —
tech-spec D-002).

Run by hand; also the engine behind sync.sh's workflow step:

    tools/workflow-defs.py                # (re)write both committed files
    tools/workflow-defs.py --check        # verify committed files match
    tools/workflow-defs.py --out DIR      # write into DIR instead
    tools/workflow-defs.py --list         # print dialect + target mapping

Exit: 0 written/verified · 1 drift or missing artifact · 2 usage error.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PKG_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = PKG_ROOT / "skills" / "spec-to-prod" / "workflows"

# The shared loop contract, embedded verbatim in both dialects as the
# header note (single source for humans; the parity test checks the
# mechanical tokens it names in BOTH files).
CONTRACT_NOTE = """\
Loop contract (mirrors scripts/graph.py --run; graph.py is the only oracle):
  1. state   = graph.py <spec-dir> --state-json
  2. gates   = clarify READY | research-gate undetermined | before-audit
               READY | approve READY | closing-audit due | tick-commit due
               -> STOP: AWAITING HUMAN <gate> (never auto-satisfied; rerun
               after the human answers — doc state is the only state)
  3. wave    = frontier agent nodes (survey research plan tech qa tasks
               execute) -> graph.py --emit-spawns writes one payload per
               agent (per runnable task under execute); spawn them all in
               one wave, each agent reads its payload file and writes its
               artifact to disk
  4. stop    = gate | complete (archive-ready / every node done) | held
               (no agent node runnable) | max-waves | no doc-state change
Generated by tools/workflow-defs.py — regenerate-only, never hand-edit.
Target runtime: zcode dynamic workflows (CreateWorkflow saved by name).\
"""

# --- zcode dialect ---------------------------------------------------------
# Facade constraints honored here: plain TypeScript function-body syntax
# (no import/export/declare tokens — checked by the invariant test), a
# /* zcode-workflow */ metadata block with the documented fields only
# (description / whenToUse / args; the file name carries the workflow
# name), compile-time-literal phase() names (the loop's iterations
# continue the same-named phase — tech-spec D-005), world.run with a
# literal command and runtime args, and a final return of the report.
DWF_TS = r'''/* zcode-workflow
description: >-
  Run the spec-to-prod frontier loop for one spec: compute the ready wave
  from doc state, spawn it as subagents, recompute — until a human gate
  (clarify, research-gate, before-audit, approve, closing-audit,
  tick-commit) or completion. graph.py is the only oracle; rerunning
  after each gate resumes from doc state.
whenToUse: >-
  Use when the user asks to run or continue a spec-to-prod spec on zcode
  ("run the auth spec pipeline", "continue the spec", "work the frontier").
args:
  spec:
    type: string
    description: The spec name — the specs/<spec>/ directory.
    required: true
  skill_dir:
    type: string
    description: Absolute skill dir override (defaults to the path baked at install time).
  max_waves:
    type: number
    description: Wave cap for this run (default 12).
*/
// ---------------------------------------------------------------------------
// spec-run.dwf.ts — the zcode dialect of the spec-to-prod frontier loop.
// __SKILL_DIR__ below is a placeholder; tools/install-workflow.sh bakes the
// active skill dir into the installed copy (a runtime skill_dir arg wins).
// ---------------------------------------------------------------------------
/*
__CONTRACT__
--------------------------------------------------------------------------- */

interface NodeState {
  state: string;
  reason?: string;
}

interface GraphState {
  spec_dir: string;
  status?: string | null;
  nodes: Record<string, NodeState>;
  frontier: string[];
  counts: Record<string, number>;
}

interface WaveDigest {
  status: string;
  digest: string;
}

interface Payload {
  path: string;
  role: string;
  node: string;
}

interface Stop {
  kind: "gate" | "complete" | "held" | "max-waves" | "no-change" | "error";
  gate?: string;
  need?: string;
  detail?: string;
}

const SKILL_DIR_BAKED = "__SKILL_DIR__";
const skillDir =
  typeof args.skill_dir === "string" && args.skill_dir
    ? args.skill_dir
    : SKILL_DIR_BAKED;
const specName = String(args.spec ?? "");
const MAX_WAVES =
  typeof args.max_waves === "number" && args.max_waves > 0
    ? args.max_waves
    : 12;

// graph.py's frontier agent nodes (everything a wave can spawn).
const AGENT_NODES = ["survey", "research", "plan", "tech", "qa", "tasks", "execute"];

function nodeState(st: GraphState, name: string): string {
  const n = st.nodes[name];
  return n ? n.state : "blocked";
}

function nodeReason(st: GraphState, name: string): string {
  const n = st.nodes[name];
  return n && n.reason ? n.reason : "";
}

// The find_pause set from graph.py, read off --state-json — a human gate
// is never auto-satisfied: stop and name what is needed.
function findPause(st: GraphState): Stop | null {
  if (nodeState(st, "clarify") === "READY") {
    return { kind: "gate", gate: "clarify", need: nodeReason(st, "clarify") };
  }
  if (nodeState(st, "research-gate") === "gate:undetermined") {
    return {
      kind: "gate",
      gate: "research-gate",
      need:
        nodeReason(st, "research-gate") +
        " — decide run (spawn the researcher; --emit-spawns prepared its payload) " +
        "or skip (write the not-applicable marker line to research.md), then rerun",
    };
  }
  if (nodeState(st, "before-audit") === "READY") {
    return {
      kind: "gate",
      gate: "before-audit",
      need:
        "run the six before-audit gates (gates/before-audit.md), then record " +
        "`Before-audit: passed @ <sha-or-dash>` in task.md",
    };
  }
  if (nodeState(st, "approve") === "READY") {
    return { kind: "gate", gate: "approve", need: nodeReason(st, "approve") };
  }
  if (nodeState(st, "execute") === "done" && nodeState(st, "closing-audit") !== "done") {
    return {
      kind: "gate",
      gate: "closing-audit",
      need:
        "run the closing audit: audit.py proofs <spec-dir> --run, scope and " +
        "clean, audit.py dod; rule on the findings, surface every D-###, get " +
        "the user's ack",
    };
  }
  if (nodeState(st, "closing-audit") === "done" && st.status !== "done") {
    return {
      kind: "gate",
      gate: "tick-commit",
      need:
        "tick every task with its proof (scripts/tick.py), fix the burndown " +
        "(check.py --fix-burndown), set spec.md Status: done, repoint INDEX.md",
    };
  }
  return null;
}

async function graphState(): Promise<GraphState | null> {
  const r = await world.run("python3", [
    skillDir + "/scripts/graph.py",
    "specs/" + specName,
    "--state-json",
  ]);
  if (r.exitCode !== 0) {
    log("graph.py --state-json failed (exit " + r.exitCode + ")");
    if (r.stderr.trim()) log(r.stderr.trim().split("\n").slice(-4).join("\n"));
    return null;
  }
  return JSON.parse(r.stdout) as GraphState;
}

async function emitPayloads(): Promise<Payload[]> {
  const r = await world.run("python3", [
    skillDir + "/scripts/graph.py",
    "specs/" + specName,
    "--emit-spawns",
  ]);
  if (r.exitCode !== 0) {
    log("graph.py --emit-spawns failed (exit " + r.exitCode + ")");
    return [];
  }
  const out: Payload[] = [];
  const re = /^ {3}payload: (\S+) \(role: (\S+), node: (\S+)\)$/gm;
  for (const mm of r.stdout.matchAll(re)) {
    out.push({ path: mm[1], role: mm[2], node: mm[3] });
  }
  return out;
}

function askText(p: Payload): string {
  return (
    "You are a spec-to-prod role agent (role: " + p.role + ", node: " + p.node + ").\n" +
    "Read your complete spawn payload file FIRST — it holds your brief, the shared\n" +
    "protocol, and your filled input payload:\n  " + p.path + "\n" +
    "Follow it exactly: write your artifact to disk under the spec dir as the brief\n" +
    "directs. Never tick task.md checkboxes, never spawn other agents, never commit.\n" +
    'Return JSON: {"status": "done" | "blocked" | "gap", "digest": "<your brief\'s digest fields, compact>"}.'
  );
}

if (!specName) {
  log("usage: run spec-run with args {\"spec\": \"<name>\"}");
} else {
  log("spec-run: " + specName + " · skill_dir: " + skillDir + " · max_waves: " + MAX_WAVES);

  phase("Read doc state and check the human gates");
  let st = await graphState();
  if (!st) {
    return { spec: specName, error: "graph.py --state-json failed — see log" };
  }

  phase("Run the ready wave");
  let waves = 0;
  let stop: Stop | null = null;
  const allDigests: { wave: number; role: string; status: string; digest: string }[] = [];

  while (!stop) {
    const pause = findPause(st);
    if (pause) {
      stop = pause;
      break;
    }
    const waveNodes = st.frontier.filter((n) => AGENT_NODES.indexOf(n) !== -1);
    if (waveNodes.length === 0) {
      if (nodeState(st, "archive") === "READY") {
        stop = { kind: "complete", detail: "archive-ready: run scripts/archive.sh " + specName };
        break;
      }
      const blocked: string[] = [];
      for (const name of Object.keys(st.nodes)) {
        if (nodeState(st, name) === "blocked") {
          blocked.push(name + ": " + nodeReason(st, name));
        }
      }
      stop = { kind: "held", detail: "no agent node runnable — blocked: " + blocked.join(" | ") };
      break;
    }
    log("wave " + (waves + 1) + " — frontier: " + waveNodes.join(", "));
    const payloads = await emitPayloads();
    if (payloads.length === 0) {
      stop = { kind: "error", detail: "--emit-spawns wrote no payloads for frontier " + waveNodes.join(", ") };
      break;
    }
    const digests = await Promise.all(
      payloads.map((p) => {
        const stem = (p.path.split("/").pop() ?? "agent").replace(/\.md$/, "");
        return agent("w" + (waves + 1) + "-" + stem).ask<WaveDigest>(askText(p));
      })
    );
    for (let i = 0; i < payloads.length; i++) {
      const d = digests[i];
      allDigests.push({ wave: waves + 1, role: payloads[i].role, status: d.status, digest: d.digest });
      log("  " + payloads[i].role + " → " + d.status + (d.status === "done" ? "" : ": " + d.digest));
    }
    waves++;
    const before = JSON.stringify(st);
    st = await graphState();
    if (!st) {
      stop = { kind: "error", detail: "graph.py --state-json failed after the wave" };
      break;
    }
    if (waves >= MAX_WAVES) {
      stop = { kind: "max-waves", detail: "wave cap " + MAX_WAVES + " reached" };
      break;
    }
    if (JSON.stringify(st) === before) {
      stop = { kind: "no-change", detail: "no doc-state change after the wave — act on the digests, then rerun" };
      break;
    }
  }

  phase("Recompute and summarize");
  const finalSt = await graphState();
  const finalStop: Stop = stop ?? { kind: "no-change", detail: "loop exited without a stop" };
  const report = {
    spec: specName,
    waves_run: waves,
    stop: finalStop,
    status: finalSt ? finalSt.status : null,
    counts: finalSt ? finalSt.counts : null,
    digests: allDigests,
  };
  if (finalStop.kind === "gate") {
    log("AWAITING HUMAN: " + finalStop.gate + ": " + finalStop.need);
  }
  if (finalSt) {
    const c = finalSt.counts;
    log(
      "state: Status " + (finalSt.status ?? "none") +
      " · tasks " + c.todo + " todo / " + c.claimed + " claimed / " + c.ticked + " ticked / " + c.struck + " struck"
    );
  }
  const lines = ["# spec-run — " + specName, ""];
  lines.push("- stop: " + finalStop.kind + (finalStop.gate ? " (" + finalStop.gate + ")" : ""));
  if (finalStop.need) lines.push("- need: " + finalStop.need);
  if (finalStop.detail) lines.push("- detail: " + finalStop.detail);
  lines.push("- waves run: " + waves);
  if (finalSt) {
    lines.push("- Status: " + (finalSt.status ?? "none"));
    const c = finalSt.counts;
    lines.push("- tasks: " + c.todo + " todo · " + c.claimed + " claimed · " + c.ticked + " ticked · " + c.struck + " struck");
  }
  if (allDigests.length) {
    lines.push("", "## Wave digests", "");
    for (const d of allDigests) {
      lines.push("- w" + d.wave + " " + d.role + " → **" + d.status + "** — " + d.digest);
    }
  }
  try {
    await artifact.markdown("run-summary", lines.join("\n"), {
      title: "spec-run — " + specName,
      description: "Frontier-loop run report; rerun the workflow after each human gate to resume.",
    });
  } catch (e) {
    log("run summary not published: " + String(e));
  }
  return report;
}
'''

# --- claude-code dialect ---------------------------------------------------
# Runtime rules honored here (Claude Code dynamic workflows): plain
# JavaScript with top-level await, `export const meta` as the FIRST
# statement, no module loading, no direct filesystem/shell access in the
# script (only subagents act — one graph-probe agent runs graph.py and
# returns stdout verbatim through a schema), deterministic primitives
# only (no Date.now / Math.random), agent results schema-validated, and
# pipeline(items, fn) mapping payloads to one agent each (nulls filtered).
WF_JS = r'''export const meta = {
  name: "spec-run",
  description:
    "Run the spec-to-prod frontier loop for one spec: compute the ready " +
    "wave from doc state, spawn it as subagents, recompute — until a human " +
    "gate (clarify, research-gate, before-audit, approve, closing-audit, " +
    "tick-commit) or completion. graph.py is the only oracle; rerunning " +
    "after each gate resumes from doc state.",
}

// ---------------------------------------------------------------------------
// spec-run.js — the Claude Code dialect of the spec-to-prod frontier loop.
// __SKILL_DIR__ below is a placeholder; tools/install-workflow.sh bakes the
// active skill dir into the installed copy (a runtime skill_dir arg wins).
// This script has NO filesystem/shell access of its own (runtime rule) —
// the graph-probe agent below is the single seam that runs graph.py.
// ---------------------------------------------------------------------------
/*
__CONTRACT__
--------------------------------------------------------------------------- */

const SKILL_DIR_BAKED = "__SKILL_DIR__";
const skillDir =
  typeof args !== "undefined" && args && typeof args.skill_dir === "string" && args.skill_dir
    ? args.skill_dir
    : SKILL_DIR_BAKED;
const specName =
  typeof args !== "undefined" && args && args.spec ? String(args.spec) : "";
const MAX_WAVES =
  typeof args !== "undefined" && args && typeof args.max_waves === "number" && args.max_waves > 0
    ? args.max_waves
    : 12;

// graph.py's frontier agent nodes (everything a wave can spawn).
const AGENT_NODES = ["survey", "research", "plan", "tech", "qa", "tasks", "execute"];

const PROBE_SCHEMA = {
  type: "object",
  properties: { stdout: { type: "string" } },
  required: ["stdout"],
  additionalProperties: false,
};

const DIGEST_SCHEMA = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["done", "blocked", "gap"] },
    digest: { type: "string" },
  },
  required: ["status", "digest"],
  additionalProperties: false,
};

function nodeState(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n ? n.state : "blocked";
}

function nodeReason(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n && n.reason ? n.reason : "";
}

// The find_pause set from graph.py, read off --state-json — a human gate
// is never auto-satisfied: stop and name what is needed.
function findPause(st) {
  if (nodeState(st, "clarify") === "READY") {
    return { kind: "gate", gate: "clarify", need: nodeReason(st, "clarify") };
  }
  if (nodeState(st, "research-gate") === "gate:undetermined") {
    return {
      kind: "gate",
      gate: "research-gate",
      need:
        nodeReason(st, "research-gate") +
        " — decide run (spawn the researcher; --emit-spawns prepared its payload) " +
        "or skip (write the not-applicable marker line to research.md), then rerun",
    };
  }
  if (nodeState(st, "before-audit") === "READY") {
    return {
      kind: "gate",
      gate: "before-audit",
      need:
        "run the six before-audit gates (gates/before-audit.md), then record " +
        "`Before-audit: passed @ <sha-or-dash>` in task.md",
    };
  }
  if (nodeState(st, "approve") === "READY") {
    return { kind: "gate", gate: "approve", need: nodeReason(st, "approve") };
  }
  if (nodeState(st, "execute") === "done" && nodeState(st, "closing-audit") !== "done") {
    return {
      kind: "gate",
      gate: "closing-audit",
      need:
        "run the closing audit: audit.py proofs <spec-dir> --run, scope and " +
        "clean, audit.py dod; rule on the findings, surface every D-###, get " +
        "the user's ack",
    };
  }
  if (nodeState(st, "closing-audit") === "done" && st.status !== "done") {
    return {
      kind: "gate",
      gate: "tick-commit",
      need:
        "tick every task with its proof (scripts/tick.py), fix the burndown " +
        "(check.py --fix-burndown), set spec.md Status: done, repoint INDEX.md",
    };
  }
  return null;
}

// One probe agent per call: runs graph.py with the given flag and returns
// its stdout verbatim (the script itself has no shell — runtime rule).
async function runGraph(flag) {
  const probe = await agent(
    "Run this exact shell command from the repo root and return ONLY its " +
      "stdout verbatim in the stdout field (empty string if none):\n" +
      "  python3 " + skillDir + "/scripts/graph.py specs/" + specName + " " + flag,
    { label: "graph-probe", schema: PROBE_SCHEMA }
  );
  return probe ? probe.stdout : null;
}

async function graphState() {
  const out = await runGraph("--state-json");
  if (!out || !out.trim()) {
    log("graph.py --state-json returned nothing — is the spec name right?");
    return null;
  }
  try {
    return JSON.parse(out);
  } catch (e) {
    log("graph.py --state-json output is not JSON: " + String(e));
    return null;
  }
}

async function emitPayloads() {
  const out = await runGraph("--emit-spawns");
  if (!out) return [];
  const payloads = [];
  const re = /^ {3}payload: (\S+) \(role: (\S+), node: (\S+)\)$/gm;
  for (const mm of out.matchAll(re)) {
    payloads.push({ path: mm[1], role: mm[2], node: mm[3] });
  }
  return payloads;
}

function askText(p) {
  return (
    "You are a spec-to-prod role agent (role: " + p.role + ", node: " + p.node + ").\n" +
    "Read your complete spawn payload file FIRST — it holds your brief, the shared\n" +
    "protocol, and your filled input payload:\n  " + p.path + "\n" +
    "Follow it exactly: write your artifact to disk under the spec dir as the brief\n" +
    "directs. Never tick task.md checkboxes, never spawn other agents, never commit.\n" +
    'Return JSON: {"status": "done" | "blocked" | "gap", "digest": "<your brief\'s digest fields, compact>"}.'
  );
}

async function main() {
  if (!specName) {
    log('usage: run spec-run with args {"spec": "<name>"}');
    return { spec: null, error: "missing arg: spec" };
  }
  log("spec-run: " + specName + " · skill_dir: " + skillDir + " · max_waves: " + MAX_WAVES);

  phase("Read doc state and check the human gates");
  let st = await graphState();
  if (!st) return { spec: specName, error: "graph.py --state-json failed — see log" };

  phase("Run the ready wave");
  let waves = 0;
  let stop = null;
  const allDigests = [];

  while (!stop) {
    const pause = findPause(st);
    if (pause) {
      stop = pause;
      break;
    }
    const waveNodes = st.frontier.filter((n) => AGENT_NODES.indexOf(n) !== -1);
    if (waveNodes.length === 0) {
      if (nodeState(st, "archive") === "READY") {
        stop = { kind: "complete", detail: "archive-ready: run scripts/archive.sh " + specName };
        break;
      }
      const blocked = [];
      for (const name of Object.keys(st.nodes)) {
        if (nodeState(st, name) === "blocked") blocked.push(name + ": " + nodeReason(st, name));
      }
      stop = { kind: "held", detail: "no agent node runnable — blocked: " + blocked.join(" | ") };
      break;
    }
    log("wave " + (waves + 1) + " — frontier: " + waveNodes.join(", "));
    const payloads = await emitPayloads();
    if (payloads.length === 0) {
      stop = { kind: "error", detail: "--emit-spawns wrote no payloads for frontier " + waveNodes.join(", ") };
      break;
    }
    phase("Wave " + (waves + 1) + " — " + waveNodes.join(" | "));
    const results = await pipeline(payloads, (p) =>
      agent(askText(p), { label: p.role, schema: DIGEST_SCHEMA })
    );
    const digests = results.filter(Boolean);
    for (const d of digests) {
      allDigests.push({ wave: waves + 1, role: d.role || "agent", status: d.status, digest: d.digest });
      log("  " + (d.role || "agent") + " → " + d.status + (d.status === "done" ? "" : ": " + d.digest));
    }
    waves++;
    const before = JSON.stringify(st);
    st = await graphState();
    if (!st) {
      stop = { kind: "error", detail: "graph.py --state-json failed after the wave" };
      break;
    }
    if (waves >= MAX_WAVES) {
      stop = { kind: "max-waves", detail: "wave cap " + MAX_WAVES + " reached" };
      break;
    }
    if (JSON.stringify(st) === before) {
      stop = { kind: "no-change", detail: "no doc-state change after the wave — act on the digests, then rerun" };
      break;
    }
  }

  phase("Recompute and summarize");
  const finalSt = await graphState();
  const report = {
    spec: specName,
    waves_run: waves,
    stop: stop,
    status: finalSt ? finalSt.status : null,
    counts: finalSt ? finalSt.counts : null,
    digests: allDigests,
  };
  if (stop && stop.kind === "gate") {
    log("AWAITING HUMAN: " + stop.gate + ": " + stop.need);
  }
  if (finalSt) {
    const c = finalSt.counts;
    log(
      "state: Status " + (finalSt.status || "none") +
        " · tasks " + c.todo + " todo / " + c.claimed + " claimed / " + c.ticked + " ticked / " + c.struck + " struck"
    );
  }
  return report;
}

const result = await main();
if (result && result.error) {
  log("spec-run stopped on error: " + result.error);
}
result;
'''

# dialect -> (filename, target harness roots' suffixes) — the installer
# owns the actual root mapping; this table is the review surface.
DIALECTS = {
    "zcode": ("spec-run.dwf.ts", DWF_TS),
    "claude": ("spec-run.js", WF_JS),
}


def render(dialect: str) -> str:
    """The dialect's file text with the shared contract note embedded."""
    _, template = DIALECTS[dialect]
    return template.replace("__CONTRACT__", CONTRACT_NOTE)


def write_all(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for dialect, (filename, _) in DIALECTS.items():
        path = out_dir / filename
        path.write_text(render(dialect), encoding="utf-8")
        written.append(path)
    return written


def check_all(out_dir: Path) -> int:
    """0 iff every committed artifact matches a fresh regeneration."""
    bad = 0
    for dialect, (filename, _) in DIALECTS.items():
        path = out_dir / filename
        if not path.exists():
            print(f"MISSING {path}")
            bad = 1
            continue
        if path.read_text(encoding="utf-8") == render(dialect):
            print(f"OK  {path}")
        else:
            print(f"DRIFT {path} — regenerate (tools/workflow-defs.py) or fix the template")
            bad = 1
    return bad


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="workflow-defs.py",
        description="Generate the spec-to-prod dynamic-workflow dialects "
                    "(zcode .dwf.ts + claude-code .js) as committed "
                    "regenerate-only artifacts (ADR-019).",
        epilog="exit codes: 0 written/verified · 1 drift or missing artifact · "
               "2 usage error")
    p.add_argument("--out", metavar="DIR", type=Path,
                   help="write into DIR instead of skills/spec-to-prod/workflows/")
    p.add_argument("--check", action="store_true",
                   help="verify the committed artifacts match a fresh "
                        "regeneration; exit 1 on drift or missing files")
    p.add_argument("--list", action="store_true",
                   help="print the dialect → filename → harness-root mapping "
                        "and exit")
    args = p.parse_args(argv)

    if args.list:
        print("dialect   filename            installed by tools/install-workflow.sh")
        print("zcode     spec-run.dwf.ts     ~/.zcode/workflows/ or <repo>/.zcode/workflows/")
        print("claude    spec-run.js         ~/.claude/workflows/ or <repo>/.claude/workflows/")
        return 0

    out_dir = args.out if args.out else WORKFLOWS_DIR
    if args.check:
        return check_all(out_dir)
    for path in write_all(out_dir):
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
