export const meta = {
  name: "spec-run",
  description:
    "Run the spec-to-prod frontier loop for one spec: compute the ready " +
    "wave from doc state, spawn it as subagents, recompute — until a human " +
    "gate (clarify, research-gate, before-audit, approve, closing-audit, " +
    "tick-commit) or completion. graph.py is the only oracle; rerunning " +
    "after each gate resumes from doc state.",
}

// ---------------------------------------------------------------------------
// spec-run.js — the Claude Code dialect of the spec-to-prod frontier loop.
// __SKILL_DIR__ below is a placeholder; tools/install-workflow.sh bakes the
// active skill dir into the installed copy (a runtime skill_dir arg wins).
// This script has NO filesystem/shell access of its own (runtime rule) —
// the graph-probe agent below is the single seam that runs graph.py.
// ---------------------------------------------------------------------------
/*
Loop contract (mirrors scripts/graph.py --run; graph.py is the only oracle):
  1. state   = graph.py <spec-dir> --state-json
  2. gates   = clarify READY | research-gate undetermined | before-audit
               READY | approve READY | closing-audit due | tick-commit due
               -> STOP: AWAITING HUMAN <gate> (never auto-satisfied; rerun
               after the human answers — doc state is the only state)
  3. wave    = frontier agent nodes (survey research plan tech qa tasks
               execute) -> graph.py --emit-spawns writes one payload per
               agent (per runnable task under execute); spawn them all in
               one wave, each agent reads its payload file and writes its
               artifact to disk
  4. stop    = gate | complete (archive-ready / every node done) | held
               (no agent node runnable) | max-waves | no doc-state change
Generated by tools/workflow-defs.py — regenerate-only, never hand-edit.
Target runtime: zcode dynamic workflows (CreateWorkflow saved by name).
--------------------------------------------------------------------------- */

const SKILL_DIR_BAKED = "__SKILL_DIR__";
const skillDir =
  typeof args !== "undefined" && args && typeof args.skill_dir === "string" && args.skill_dir
    ? args.skill_dir
    : SKILL_DIR_BAKED;
const specName =
  typeof args !== "undefined" && args && args.spec ? String(args.spec) : "";
const MAX_WAVES =
  typeof args !== "undefined" && args && typeof args.max_waves === "number" && args.max_waves > 0
    ? args.max_waves
    : 12;

// graph.py's frontier agent nodes (everything a wave can spawn).
const AGENT_NODES = ["survey", "research", "plan", "tech", "qa", "tasks", "execute"];

const PROBE_SCHEMA = {
  type: "object",
  properties: { stdout: { type: "string" } },
  required: ["stdout"],
  additionalProperties: false,
};

const DIGEST_SCHEMA = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["done", "blocked", "gap"] },
    digest: { type: "string" },
  },
  required: ["status", "digest"],
  additionalProperties: false,
};

function nodeState(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n ? n.state : "blocked";
}

function nodeReason(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n && n.reason ? n.reason : "";
}

// The find_pause set from graph.py, read off --state-json — a human gate
// is never auto-satisfied: stop and name what is needed.
function findPause(st) {
  if (nodeState(st, "clarify") === "READY") {
    return { kind: "gate", gate: "clarify", need: nodeReason(st, "clarify") };
  }
  if (nodeState(st, "research-gate") === "gate:undetermined") {
    return {
      kind: "gate",
      gate: "research-gate",
      need:
        nodeReason(st, "research-gate") +
        " — decide run (spawn the researcher; --emit-spawns prepared its payload) " +
        "or skip (write the not-applicable marker line to research.md), then rerun",
    };
  }
  if (nodeState(st, "before-audit") === "READY") {
    return {
      kind: "gate",
      gate: "before-audit",
      need:
        "run the six before-audit gates (gates/before-audit.md), then record " +
        "`Before-audit: passed @ <sha-or-dash>` in task.md",
    };
  }
  if (nodeState(st, "approve") === "READY") {
    return { kind: "gate", gate: "approve", need: nodeReason(st, "approve") };
  }
  if (nodeState(st, "execute") === "done" && nodeState(st, "closing-audit") !== "done") {
    return {
      kind: "gate",
      gate: "closing-audit",
      need:
        "run the closing audit: audit.py proofs <spec-dir> --run, scope and " +
        "clean, audit.py dod; rule on the findings, surface every D-###, get " +
        "the user's ack",
    };
  }
  if (nodeState(st, "closing-audit") === "done" && st.status !== "done") {
    return {
      kind: "gate",
      gate: "tick-commit",
      need:
        "tick every task with its proof (scripts/tick.py), fix the burndown " +
        "(check.py --fix-burndown), set spec.md Status: done, repoint INDEX.md",
    };
  }
  return null;
}

// One probe agent per call: runs graph.py with the given flag and returns
// its stdout verbatim (the script itself has no shell — runtime rule).
async function runGraph(flag) {
  const probe = await agent(
    "Run this exact shell command from the repo root and return ONLY its " +
      "stdout verbatim in the stdout field (empty string if none):\n" +
      "  python3 " + skillDir + "/scripts/graph.py specs/" + specName + " " + flag,
    { label: "graph-probe", schema: PROBE_SCHEMA }
  );
  return probe ? probe.stdout : null;
}

async function graphState() {
  const out = await runGraph("--state-json");
  if (!out || !out.trim()) {
    log("graph.py --state-json returned nothing — is the spec name right?");
    return null;
  }
  try {
    return JSON.parse(out);
  } catch (e) {
    log("graph.py --state-json output is not JSON: " + String(e));
    return null;
  }
}

async function emitPayloads() {
  const out = await runGraph("--emit-spawns");
  if (!out) return [];
  const payloads = [];
  const re = /^ {3}payload: (\S+) \(role: (\S+), node: (\S+)\)$/gm;
  for (const mm of out.matchAll(re)) {
    payloads.push({ path: mm[1], role: mm[2], node: mm[3] });
  }
  return payloads;
}

function askText(p) {
  return (
    "You are a spec-to-prod role agent (role: " + p.role + ", node: " + p.node + ").\n" +
    "Read your complete spawn payload file FIRST — it holds your brief, the shared\n" +
    "protocol, and your filled input payload:\n  " + p.path + "\n" +
    "Follow it exactly: write your artifact to disk under the spec dir as the brief\n" +
    "directs. Never tick task.md checkboxes, never spawn other agents, never commit.\n" +
    'Return JSON: {"status": "done" | "blocked" | "gap", "digest": "<your brief\'s digest fields, compact>"}.'
  );
}

async function main() {
  if (!specName) {
    log('usage: run spec-run with args {"spec": "<name>"}');
    return { spec: null, error: "missing arg: spec" };
  }
  log("spec-run: " + specName + " · skill_dir: " + skillDir + " · max_waves: " + MAX_WAVES);

  phase("Read doc state and check the human gates");
  let st = await graphState();
  if (!st) return { spec: specName, error: "graph.py --state-json failed — see log" };

  phase("Run the ready wave");
  let waves = 0;
  let stop = null;
  const allDigests = [];

  while (!stop) {
    const pause = findPause(st);
    if (pause) {
      stop = pause;
      break;
    }
    const waveNodes = st.frontier.filter((n) => AGENT_NODES.indexOf(n) !== -1);
    if (waveNodes.length === 0) {
      if (nodeState(st, "archive") === "READY") {
        stop = { kind: "complete", detail: "archive-ready: run scripts/archive.sh " + specName };
        break;
      }
      const blocked = [];
      for (const name of Object.keys(st.nodes)) {
        if (nodeState(st, name) === "blocked") blocked.push(name + ": " + nodeReason(st, name));
      }
      stop = { kind: "held", detail: "no agent node runnable — blocked: " + blocked.join(" | ") };
      break;
    }
    log("wave " + (waves + 1) + " — frontier: " + waveNodes.join(", "));
    const payloads = await emitPayloads();
    if (payloads.length === 0) {
      stop = { kind: "error", detail: "--emit-spawns wrote no payloads for frontier " + waveNodes.join(", ") };
      break;
    }
    phase("Wave " + (waves + 1) + " — " + waveNodes.join(" | "));
    const results = await pipeline(payloads, (p) =>
      agent(askText(p), { label: p.role, schema: DIGEST_SCHEMA })
    );
    const digests = results.filter(Boolean);
    for (const d of digests) {
      allDigests.push({ wave: waves + 1, role: d.role || "agent", status: d.status, digest: d.digest });
      log("  " + (d.role || "agent") + " → " + d.status + (d.status === "done" ? "" : ": " + d.digest));
    }
    waves++;
    const before = JSON.stringify(st);
    st = await graphState();
    if (!st) {
      stop = { kind: "error", detail: "graph.py --state-json failed after the wave" };
      break;
    }
    if (waves >= MAX_WAVES) {
      stop = { kind: "max-waves", detail: "wave cap " + MAX_WAVES + " reached" };
      break;
    }
    if (JSON.stringify(st) === before) {
      stop = { kind: "no-change", detail: "no doc-state change after the wave — act on the digests, then rerun" };
      break;
    }
  }

  phase("Recompute and summarize");
  const finalSt = await graphState();
  const report = {
    spec: specName,
    waves_run: waves,
    stop: stop,
    status: finalSt ? finalSt.status : null,
    counts: finalSt ? finalSt.counts : null,
    digests: allDigests,
  };
  if (stop && stop.kind === "gate") {
    log("AWAITING HUMAN: " + stop.gate + ": " + stop.need);
  }
  if (finalSt) {
    const c = finalSt.counts;
    log(
      "state: Status " + (finalSt.status || "none") +
        " · tasks " + c.todo + " todo / " + c.claimed + " claimed / " + c.ticked + " ticked / " + c.struck + " struck"
    );
  }
  return report;
}

const result = await main();
if (result && result.error) {
  log("spec-run stopped on error: " + result.error);
}
result;
