export const meta = {
  name: "spec-run",
  description:
    "Run the spec-to-prod frontier loop for one spec: compute the ready " +
    "wave from doc state, spawn it as subagents, recompute — until a human " +
    "gate (clarify, research-gate, before-audit, approve, closing-audit, " +
    "tick-commit) or completion. graph.py is the only oracle; rerunning " +
    "after each gate resumes from doc state.",
}

// ---------------------------------------------------------------------------
// spec-run.js — the Claude Code dialect of the spec-to-prod frontier loop.
// __SKILL_DIR__ below is a placeholder; tools/install-workflow.sh bakes the
// active skill dir into the installed copy (a runtime skill_dir arg wins).
// This script has NO filesystem/shell access of its own (runtime rule) —
// the graph-probe agent below is the single seam that runs graph.py.
// ---------------------------------------------------------------------------
/*
Loop contract (mirrors scripts/graph.py --run; graph.py is the only oracle):
  1. state   = graph.py <spec-dir> --state-json
  2. gates   = clarify READY | research-gate undetermined | before-audit
               READY | approve READY | closing-audit due | tick-commit due
               -> STOP: AWAITING HUMAN <gate> (never auto-satisfied; rerun
               after the human answers — doc state is the only state)
  3. wave    = frontier agent nodes (survey research plan tech qa tasks
               execute) -> graph.py --emit-spawns writes one payload per
               agent (per runnable task under execute); spawn them all in
               one wave, each agent reads its payload file and writes its
               artifact to disk (one graph fetch per wave: state + emit)
  4. rebrief = a wave that changed no doc state gets exactly ONE retry
               round for its failed payloads (status blocked/gap), the
               failure digest verbatim appended to the ask; rounds 2+
               stay with the orchestrator
  5. stop    = gate | complete (archive-ready / every node done) | held
               (no agent node runnable) | max-waves | no doc-state change
               (after the re-brief round, if used)
Generated by tools/workflow-defs.py — regenerate-only, never hand-edit.
Target runtime: zcode dynamic workflows (CreateWorkflow saved by name).
--------------------------------------------------------------------------- */

const SKILL_DIR_BAKED = "__SKILL_DIR__";
const skillDir =
  typeof args !== "undefined" && args && typeof args.skill_dir === "string" && args.skill_dir
    ? args.skill_dir
    : SKILL_DIR_BAKED;
const specName =
  typeof args !== "undefined" && args && args.spec ? String(args.spec) : "";
const MAX_WAVES =
  typeof args !== "undefined" && args && typeof args.max_waves === "number" && args.max_waves > 0
    ? args.max_waves
    : 12;

// graph.py's frontier agent nodes (everything a wave can spawn).
const AGENT_NODES = ["survey", "research", "plan", "tech", "qa", "tasks", "execute"];

const PROBE_SCHEMA = {
  type: "object",
  properties: { stdout: { type: "string" } },
  required: ["stdout"],
  additionalProperties: false,
};

const DIGEST_SCHEMA = {
  type: "object",
  properties: {
    status: { type: "string", enum: ["done", "blocked", "gap"] },
    digest: { type: "string" },
  },
  required: ["status", "digest"],
  additionalProperties: false,
};

function nodeState(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n ? n.state : "blocked";
}

function nodeReason(st, name) {
  const n = st && st.nodes ? st.nodes[name] : null;
  return n && n.reason ? n.reason : "";
}

// The find_pause set from graph.py, read off --state-json — a human gate
// is never auto-satisfied: stop and name what is needed.
function findPause(st) {
  if (nodeState(st, "clarify") === "READY") {
    return { kind: "gate", gate: "clarify", need: nodeReason(st, "clarify") };
  }
  if (nodeState(st, "research-gate") === "gate:undetermined") {
    return {
      kind: "gate",
      gate: "research-gate",
      need:
        nodeReason(st, "research-gate") +
        " — decide run (spawn the researcher; --emit-spawns prepared its payload) " +
        "or skip (write the not-applicable marker line to research.md), then rerun",
    };
  }
  if (nodeState(st, "before-audit") === "READY") {
    return {
      kind: "gate",
      gate: "before-audit",
      need:
        "run the six before-audit gates (gates/before-audit.md), then record " +
        "`Before-audit: passed @ <sha-or-dash>` in task.md",
    };
  }
  if (nodeState(st, "approve") === "READY") {
    return {
      kind: "gate",
      gate: "approve",
      need:
        nodeReason(st, "approve") +
        " — after the explicit yes, run freeze.py <spec-dir> --record",
    };
  }
  if (nodeState(st, "execute") === "done" && nodeState(st, "closing-audit") !== "done") {
    return {
      kind: "gate",
      gate: "closing-audit",
      need:
        "run the closing audit: audit.py evidence, scope (from the " +
        "before-audit SHA), clean, implementation-diff review, proofs " +
        "--run, regression, and dod; record evidence/closing.md, surface " +
        "every D-###, and get the user's ack",
    };
  }
  if (nodeState(st, "closing-audit") === "done" && st.status !== "done") {
    return {
      kind: "gate",
      gate: "tick-commit",
      need:
        "tick every task with its proof (scripts/tick.py), fix the burndown, " +
        "make implementation commit C1, then delivery-record commit C2 with " +
        "Delivered: commit @ C1, Status: done, and INDEX repointed",
    };
  }
  return null;
}

// ONE probe agent per graph fetch: a single shell line runs graph.py
// twice (--state-json + --emit-spawns) and the outputs come back split
// on a marker — one agent call per wave instead of two (the script
// itself has no shell; only subagents do).
const SPLIT = "__SPLIT__";

async function fetchCycle() {
  const cmd =
    "python3 " + skillDir + "/scripts/graph.py specs/" + specName + " --state-json" +
      " && echo " + SPLIT + " && " +
      "python3 " + skillDir + "/scripts/graph.py specs/" + specName + " --emit-spawns";
  const probe = await agent(
    "Run this exact shell command from the repo root and return ONLY its " +
      "combined stdout verbatim in the stdout field (empty string if none):\n" +
      "  " + cmd,
    { label: "graph-probe", schema: PROBE_SCHEMA }
  );
  if (!probe || !probe.stdout || !probe.stdout.trim()) {
    log("graph.py returned nothing — is the spec name right?");
    return null;
  }
  const parts = probe.stdout.split(SPLIT);
  let st = null;
  try {
    st = JSON.parse(parts[0] || "");
  } catch (e) {
    log("graph.py --state-json output is not JSON: " + String(e));
    return null;
  }
  const payloads = [];
  const re = /^ {3}payload: (\S+) \(role: (\S+), node: (\S+)\)$/gm;
  for (const mm of parts.slice(1).join(SPLIT).matchAll(re)) {
    payloads.push({ path: mm[1], role: mm[2], node: mm[3] });
  }
  return { st: st, payloads: payloads };
}

function askText(p) {
  return (
    "You are a spec-to-prod role agent (role: " + p.role + ", node: " + p.node + ").\n" +
    "Read your complete spawn payload file FIRST — it holds your brief, the shared\n" +
    "protocol, and your filled input payload:\n  " + p.path + "\n" +
    "Follow it exactly: write your artifact to disk under the spec dir as the brief\n" +
    "directs. Never tick task.md checkboxes, never spawn other agents, never commit.\n" +
    'Return JSON: {"status": "done" | "blocked" | "gap", "digest": "<your brief\'s digest fields, compact>"}.'
  );
}

function rebriefText(p, d) {
  return (
    askText(p) +
    "\n\nA previous attempt at this payload returned status " + d.status +
    " with this digest:\n" + d.digest +
    "\nRe-brief round 1: address that failure evidence directly."
  );
}

async function main() {
  if (!specName) {
    log('usage: run spec-run with args {"spec": "<name>"}');
    return { spec: null, error: "missing arg: spec" };
  }
  log("spec-run: " + specName + " · skill_dir: " + skillDir + " · max_waves: " + MAX_WAVES);

  phase("Read doc state and check the human gates");
  let cycle = await fetchCycle();
  if (!cycle) return { spec: specName, error: "graph.py --state-json failed — see log" };
  let st = cycle.st;

  phase("Run the ready wave");
  let waves = 0;
  let stop = null;
  const allDigests = [];
  const retriedPaths = [];

  while (!stop) {
    const pause = findPause(st);
    if (pause) {
      stop = pause;
      break;
    }
    const waveNodes = st.frontier.filter((n) => AGENT_NODES.indexOf(n) !== -1);
    if (waveNodes.length === 0) {
      if (nodeState(st, "archive") === "READY") {
        stop = { kind: "complete", detail: "archive-ready: run scripts/archive.sh " + specName };
        break;
      }
      const blocked = [];
      for (const name of Object.keys(st.nodes)) {
        if (nodeState(st, name) === "blocked") blocked.push(name + ": " + nodeReason(st, name));
      }
      stop = { kind: "held", detail: "no agent node runnable — blocked: " + blocked.join(" | ") };
      break;
    }
    log("wave " + (waves + 1) + " — frontier: " + waveNodes.join(", "));
    const payloads = cycle.payloads;
    if (payloads.length === 0) {
      stop = { kind: "error", detail: "--emit-spawns wrote no payloads for frontier " + waveNodes.join(", ") };
      break;
    }
    phase("Wave " + (waves + 1) + " — " + waveNodes.join(" | "));
    const results = await pipeline(payloads, (p) =>
      agent(askText(p), { label: p.role, schema: DIGEST_SCHEMA })
    );
    for (let i = 0; i < payloads.length; i++) {
      const d = results[i];
      if (!d) {
        log("  " + payloads[i].role + " → no result (stopped or errored)");
        continue;
      }
      allDigests.push({ wave: waves + 1, role: payloads[i].role, status: d.status, digest: d.digest });
      log("  " + payloads[i].role + " → " + d.status + (d.status === "done" ? "" : ": " + d.digest));
    }
    waves++;
    const before = JSON.stringify(st);
    cycle = await fetchCycle();
    if (!cycle) {
      stop = { kind: "error", detail: "graph.py --state-json failed after the wave" };
      break;
    }
    st = cycle.st;
    if (JSON.stringify(st) === before) {
      // one bounded re-brief round: failed payloads retried with their
      // failure evidence verbatim (rounds 2+ stay with the orchestrator)
      const retry = [];
      for (let i = 0; i < payloads.length; i++) {
        const d = results[i];
        if (d && d.status !== "done" && d.digest
            && retriedPaths.indexOf(payloads[i].path) === -1) {
          retry.push({ p: payloads[i], d: d });
        }
      }
      if (retry.length === 0) {
        stop = { kind: "no-change", detail: "no doc-state change after the wave — act on the digests, then rerun" };
        break;
      }
      log("no doc-state change — re-brief round 1 with failure evidence: "
          + retry.map((r) => r.p.role).join(", "));
      const rd = await pipeline(retry, (r) =>
        agent(rebriefText(r.p, r.d), { label: r.p.role + "-rebrief", schema: DIGEST_SCHEMA })
      );
      for (let i = 0; i < retry.length; i++) {
        const d = rd[i];
        if (!d) continue;
        allDigests.push({ wave: waves + 1, role: retry[i].p.role, status: d.status, digest: d.digest });
        log("  " + retry[i].p.role + " (re-brief) → " + d.status);
      }
      for (const r of retry) retriedPaths.push(r.p.path);
      waves++;
      cycle = await fetchCycle();
      if (!cycle) {
        stop = { kind: "error", detail: "graph.py --state-json failed after the re-brief wave" };
        break;
      }
      st = cycle.st;
      if (JSON.stringify(st) === before) {
        stop = { kind: "no-change", detail: "no doc-state change after the re-brief round — rounds 2+ are the orchestrator's (re-brief in-session with fresh evidence), then rerun" };
        break;
      }
    }
    if (waves >= MAX_WAVES) {
      stop = { kind: "max-waves", detail: "wave cap " + MAX_WAVES + " reached" };
      break;
    }
  }

  phase("Recompute and summarize");
  // reuse the last post-wave state — no extra probe agent for the summary
  const finalSt = st;
  const report = {
    spec: specName,
    waves_run: waves,
    stop: stop,
    status: finalSt ? finalSt.status : null,
    counts: finalSt ? finalSt.counts : null,
    digests: allDigests,
  };
  if (stop && stop.kind === "gate") {
    log("AWAITING HUMAN: " + stop.gate + ": " + stop.need);
  }
  if (finalSt) {
    const c = finalSt.counts;
    log(
      "state: Status " + (finalSt.status || "none") +
        " · tasks " + c.todo + " todo / " + c.claimed + " claimed / " + c.ticked + " ticked / " + c.struck + " struck"
    );
  }
  return report;
}

const result = await main();
if (result && result.error) {
  log("spec-run stopped on error: " + result.error);
}
result;
