/* zcode-workflow
description: >-
  Run the spec-to-prod frontier loop for one spec: compute the ready wave
  from doc state, spawn it as subagents, recompute — until a human gate
  (clarify, research-gate, before-audit, approve, closing-audit,
  tick-commit) or completion. graph.py is the only oracle; rerunning
  after each gate resumes from doc state.
whenToUse: >-
  Use when the user asks to run or continue a spec-to-prod spec on zcode
  ("run the auth spec pipeline", "continue the spec", "work the frontier").
args:
  spec:
    type: string
    description: The spec name — the specs/<spec>/ directory.
    required: true
  skill_dir:
    type: string
    description: Absolute skill dir override (defaults to the path baked at install time).
  max_waves:
    type: number
    description: Wave cap for this run (default 12).
*/
// ---------------------------------------------------------------------------
// spec-run.dwf.ts — the zcode dialect of the spec-to-prod frontier loop.
// __SKILL_DIR__ below is a placeholder; tools/install-workflow.sh bakes the
// active skill dir into the installed copy (a runtime skill_dir arg wins).
// ---------------------------------------------------------------------------
/*
Loop contract (mirrors scripts/graph.py --run; graph.py is the only oracle):
  1. state   = graph.py <spec-dir> --state-json
  2. gates   = clarify READY | research-gate undetermined | before-audit
               READY | approve READY | closing-audit due | tick-commit due
               -> STOP: AWAITING HUMAN <gate> (never auto-satisfied; rerun
               after the human answers — doc state is the only state)
  3. wave    = frontier agent nodes (survey research plan tech qa tasks
               execute) -> graph.py --emit-spawns writes one payload per
               agent (per runnable task under execute); spawn them all in
               one wave, each agent reads its payload file and writes its
               artifact to disk (one graph fetch per wave: state + emit)
  4. rebrief = a wave that changed no doc state gets exactly ONE retry
               round for its failed payloads (status blocked/gap), the
               failure digest verbatim appended to the ask; rounds 2+
               stay with the orchestrator
  5. stop    = gate | complete (archive-ready / every node done) | held
               (no agent node runnable) | max-waves | no doc-state change
               (after the re-brief round, if used)
Generated by tools/workflow-defs.py — regenerate-only, never hand-edit.
Target runtime: zcode dynamic workflows (CreateWorkflow saved by name).
--------------------------------------------------------------------------- */

interface NodeState {
  state: string;
  reason?: string;
}

interface GraphState {
  spec_dir: string;
  status?: string | null;
  nodes: Record<string, NodeState>;
  frontier: string[];
  counts: Record<string, number>;
}

interface WaveDigest {
  status: string;
  digest: string;
}

interface Payload {
  path: string;
  role: string;
  node: string;
}

interface Stop {
  kind: "gate" | "complete" | "held" | "max-waves" | "no-change" | "error";
  gate?: string;
  need?: string;
  detail?: string;
}

const SKILL_DIR_BAKED = "__SKILL_DIR__";
const skillDir =
  typeof args.skill_dir === "string" && args.skill_dir
    ? args.skill_dir
    : SKILL_DIR_BAKED;
const specName = String(args.spec ?? "");
const MAX_WAVES =
  typeof args.max_waves === "number" && args.max_waves > 0
    ? args.max_waves
    : 12;

// graph.py's frontier agent nodes (everything a wave can spawn).
const AGENT_NODES = ["survey", "research", "plan", "tech", "qa", "tasks", "execute"];

function nodeState(st: GraphState, name: string): string {
  const n = st.nodes[name];
  return n ? n.state : "blocked";
}

function nodeReason(st: GraphState, name: string): string {
  const n = st.nodes[name];
  return n && n.reason ? n.reason : "";
}

// The find_pause set from graph.py, read off --state-json — a human gate
// is never auto-satisfied: stop and name what is needed.
function findPause(st: GraphState): Stop | null {
  if (nodeState(st, "clarify") === "READY") {
    return { kind: "gate", gate: "clarify", need: nodeReason(st, "clarify") };
  }
  if (nodeState(st, "research-gate") === "gate:undetermined") {
    return {
      kind: "gate",
      gate: "research-gate",
      need:
        nodeReason(st, "research-gate") +
        " — decide run (spawn the researcher; --emit-spawns prepared its payload) " +
        "or skip (write the not-applicable marker line to research.md), then rerun",
    };
  }
  if (nodeState(st, "before-audit") === "READY") {
    return {
      kind: "gate",
      gate: "before-audit",
      need:
        "run the six before-audit gates (gates/before-audit.md), then record " +
        "`Before-audit: passed @ <sha-or-dash>` in task.md",
    };
  }
  if (nodeState(st, "approve") === "READY") {
    return { kind: "gate", gate: "approve", need: nodeReason(st, "approve") };
  }
  if (nodeState(st, "execute") === "done" && nodeState(st, "closing-audit") !== "done") {
    return {
      kind: "gate",
      gate: "closing-audit",
      need:
        "run the closing audit: audit.py proofs <spec-dir> --run, scope and " +
        "clean, audit.py dod; rule on the findings, surface every D-###, get " +
        "the user's ack",
    };
  }
  if (nodeState(st, "closing-audit") === "done" && st.status !== "done") {
    return {
      kind: "gate",
      gate: "tick-commit",
      need:
        "tick every task with its proof (scripts/tick.py), fix the burndown " +
        "(check.py --fix-burndown), set spec.md Status: done, repoint INDEX.md",
    };
  }
  return null;
}

async function graphState(): Promise<GraphState | null> {
  const r = await world.run("python3", [
    skillDir + "/scripts/graph.py",
    "specs/" + specName,
    "--state-json",
  ]);
  if (r.exitCode !== 0) {
    log("graph.py --state-json failed (exit " + r.exitCode + ")");
    if (r.stderr.trim()) log(r.stderr.trim().split("\n").slice(-4).join("\n"));
    return null;
  }
  return JSON.parse(r.stdout) as GraphState;
}

async function emitPayloads(): Promise<Payload[]> {
  const r = await world.run("python3", [
    skillDir + "/scripts/graph.py",
    "specs/" + specName,
    "--emit-spawns",
  ]);
  if (r.exitCode !== 0) {
    log("graph.py --emit-spawns failed (exit " + r.exitCode + ")");
    return [];
  }
  const out: Payload[] = [];
  const re = /^ {3}payload: (\S+) \(role: (\S+), node: (\S+)\)$/gm;
  for (const mm of r.stdout.matchAll(re)) {
    out.push({ path: mm[1], role: mm[2], node: mm[3] });
  }
  return out;
}

function askText(p: Payload): string {
  return (
    "You are a spec-to-prod role agent (role: " + p.role + ", node: " + p.node + ").\n" +
    "Read your complete spawn payload file FIRST — it holds your brief, the shared\n" +
    "protocol, and your filled input payload:\n  " + p.path + "\n" +
    "Follow it exactly: write your artifact to disk under the spec dir as the brief\n" +
    "directs. Never tick task.md checkboxes, never spawn other agents, never commit.\n" +
    'Return JSON: {"status": "done" | "blocked" | "gap", "digest": "<your brief\'s digest fields, compact>"}.'
  );
}

function rebriefText(p: Payload, d: WaveDigest): string {
  return (
    askText(p) +
    "\n\nA previous attempt at this payload returned status " + d.status +
    " with this digest:\n" + d.digest +
    "\nRe-brief round 1: address that failure evidence directly."
  );
}

if (!specName) {
  log("usage: run spec-run with args {\"spec\": \"<name>\"}");
} else {
  log("spec-run: " + specName + " · skill_dir: " + skillDir + " · max_waves: " + MAX_WAVES);

  phase("Read doc state and check the human gates");
  let st = await graphState();
  if (!st) {
    return { spec: specName, error: "graph.py --state-json failed — see log" };
  }

  phase("Run the ready wave");
  let waves = 0;
  let stop: Stop | null = null;
  const allDigests: { wave: number; role: string; status: string; digest: string }[] = [];
  const retriedPaths: string[] = [];

  while (!stop) {
    const pause = findPause(st);
    if (pause) {
      stop = pause;
      break;
    }
    const waveNodes = st.frontier.filter((n) => AGENT_NODES.indexOf(n) !== -1);
    if (waveNodes.length === 0) {
      if (nodeState(st, "archive") === "READY") {
        stop = { kind: "complete", detail: "archive-ready: run scripts/archive.sh " + specName };
        break;
      }
      const blocked: string[] = [];
      for (const name of Object.keys(st.nodes)) {
        if (nodeState(st, name) === "blocked") {
          blocked.push(name + ": " + nodeReason(st, name));
        }
      }
      stop = { kind: "held", detail: "no agent node runnable — blocked: " + blocked.join(" | ") };
      break;
    }
    log("wave " + (waves + 1) + " — frontier: " + waveNodes.join(", "));
    const payloads = await emitPayloads();
    if (payloads.length === 0) {
      stop = { kind: "error", detail: "--emit-spawns wrote no payloads for frontier " + waveNodes.join(", ") };
      break;
    }
    const digests = await Promise.all(
      payloads.map((p) => {
        const stem = (p.path.split("/").pop() ?? "agent").replace(/\.md$/, "");
        return agent("w" + (waves + 1) + "-" + stem).ask<WaveDigest>(askText(p));
      })
    );
    for (let i = 0; i < payloads.length; i++) {
      const d = digests[i];
      allDigests.push({ wave: waves + 1, role: payloads[i].role, status: d.status, digest: d.digest });
      log("  " + payloads[i].role + " → " + d.status + (d.status === "done" ? "" : ": " + d.digest));
    }
    waves++;
    const before = JSON.stringify(st);
    st = await graphState();
    if (!st) {
      stop = { kind: "error", detail: "graph.py --state-json failed after the wave" };
      break;
    }
    if (JSON.stringify(st) === before) {
      // one bounded re-brief round: failed payloads retried with their
      // failure evidence verbatim (rounds 2+ stay with the orchestrator)
      const retry: { p: Payload; d: WaveDigest }[] = [];
      for (let i = 0; i < payloads.length; i++) {
        const d = digests[i];
        if (d && d.status !== "done" && d.digest
            && retriedPaths.indexOf(payloads[i].path) === -1) {
          retry.push({ p: payloads[i], d });
        }
      }
      if (retry.length === 0) {
        stop = { kind: "no-change", detail: "no doc-state change after the wave — act on the digests, then rerun" };
        break;
      }
      log("no doc-state change — re-brief round 1 with failure evidence: "
          + retry.map((r) => r.p.role).join(", "));
      const rd = await Promise.all(
        retry.map((r) => {
          const stem = (r.p.path.split("/").pop() ?? "agent").replace(/\.md$/, "");
          return agent("w" + (waves + 1) + "-" + stem + "-retry").ask<WaveDigest>(rebriefText(r.p, r.d));
        })
      );
      for (let i = 0; i < retry.length; i++) {
        const d = rd[i];
        allDigests.push({ wave: waves + 1, role: retry[i].p.role, status: d.status, digest: d.digest });
        log("  " + retry[i].p.role + " (re-brief) → " + d.status);
      }
      for (const r of retry) retriedPaths.push(r.p.path);
      waves++;
      st = await graphState();
      if (!st) {
        stop = { kind: "error", detail: "graph.py --state-json failed after the re-brief wave" };
        break;
      }
      if (JSON.stringify(st) === before) {
        stop = { kind: "no-change", detail: "no doc-state change after the re-brief round — rounds 2+ are the orchestrator's (re-brief in-session with fresh evidence), then rerun" };
        break;
      }
    }
    if (waves >= MAX_WAVES) {
      stop = { kind: "max-waves", detail: "wave cap " + MAX_WAVES + " reached" };
      break;
    }
  }

  phase("Recompute and summarize");
  const finalSt = await graphState();
  const finalStop: Stop = stop ?? { kind: "no-change", detail: "loop exited without a stop" };
  const report = {
    spec: specName,
    waves_run: waves,
    stop: finalStop,
    status: finalSt ? finalSt.status : null,
    counts: finalSt ? finalSt.counts : null,
    digests: allDigests,
  };
  if (finalStop.kind === "gate") {
    log("AWAITING HUMAN: " + finalStop.gate + ": " + finalStop.need);
  }
  if (finalSt) {
    const c = finalSt.counts;
    log(
      "state: Status " + (finalSt.status ?? "none") +
      " · tasks " + c.todo + " todo / " + c.claimed + " claimed / " + c.ticked + " ticked / " + c.struck + " struck"
    );
  }
  const lines = ["# spec-run — " + specName, ""];
  lines.push("- stop: " + finalStop.kind + (finalStop.gate ? " (" + finalStop.gate + ")" : ""));
  if (finalStop.need) lines.push("- need: " + finalStop.need);
  if (finalStop.detail) lines.push("- detail: " + finalStop.detail);
  lines.push("- waves run: " + waves);
  if (finalSt) {
    lines.push("- Status: " + (finalSt.status ?? "none"));
    const c = finalSt.counts;
    lines.push("- tasks: " + c.todo + " todo · " + c.claimed + " claimed · " + c.ticked + " ticked · " + c.struck + " struck");
  }
  if (allDigests.length) {
    lines.push("", "## Wave digests", "");
    for (const d of allDigests) {
      lines.push("- w" + d.wave + " " + d.role + " → **" + d.status + "** — " + d.digest);
    }
  }
  try {
    await artifact.markdown("run-summary", lines.join("\n"), {
      title: "spec-run — " + specName,
      description: "Frontier-loop run report; rerun the workflow after each human gate to resume.",
    });
  } catch (e) {
    log("run summary not published: " + String(e));
  }
  return report;
}
